table Códigos
	excludeFromModelRefresh
	lineageTag: 67f44533-da3f-458f-be69-8fab5cee4758

	column Código
		dataType: string
		lineageTag: 78407b8d-39c1-4a91-b06b-9886117064e5
		summarizeBy: none
		sourceColumn: Código

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 162c2a62-e1ab-490f-8720-479dbeaf8f45
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: e3b338b1-5c08-4dd4-9a99-f3b566ce9985
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	column Município
		dataType: string
		lineageTag: 927fbf6c-9f5a-4a9c-981a-d371cf7ee801
		summarizeBy: none
		sourceColumn: Município

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: 39e58316-0d93-4b83-beaf-18cb86f38020
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column 'Nome Final'
		dataType: string
		lineageTag: ceed1c17-fad8-4818-85e0-aded5ec36c5c
		summarizeBy: none
		sourceColumn: Nome Final

		annotation SummarizationSetBy = Automatic

	column 'É cliente público em operação na plataforma 2023?'
		dataType: string
		lineageTag: 70d48994-d5fd-4637-9174-5f0498fdcd3a
		summarizeBy: none
		sourceColumn: É cliente público em operação na plataforma 2023?

		annotation SummarizationSetBy = Automatic

	column 'É cliente público em operação na plataforma 2024?'
		dataType: string
		lineageTag: 499930e5-8ab2-44e7-9cc0-434eda9967ee
		summarizeBy: none
		sourceColumn: É cliente público em operação na plataforma 2024?

		annotation SummarizationSetBy = Automatic

	column 'Detalhamento de cidades/escolas'
		dataType: string
		lineageTag: 84857cf8-c1e9-452a-a724-f6e31e7c93c7
		summarizeBy: none
		sourceColumn: Detalhamento de cidades/escolas

		annotation SummarizationSetBy = Automatic

	column ID_REDE
		dataType: string
		lineageTag: c436e931-23da-42ce-9e53-78c56b276eae
		summarizeBy: none
		sourceColumn: ID_REDE

		annotation SummarizationSetBy = Automatic

	partition Códigos = m
		mode: import
		queryGroup: 'Consultas sheets'
		source =
				let
				    Fonte = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1oxWnwXoojvSDSqd8U9a4bbblxeKUsyLBr_k_lYzhT_I"),
				    #"Clientes Publico_Sheet" = Fonte{[name="Códigos",ItemKind="Table"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Clientes Publico_Sheet", [PromoteAllScalars=true]),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Cabeçalhos Promovidos", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Linhas em Branco Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

