table dAvalieasAulas
	lineageTag: 562a1937-22ac-41e9-ad26-7bbbb559fba8

	column Nome
		dataType: string
		lineageTag: 3fa8cb38-23d4-41f7-970e-4c118800d068
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Login
		dataType: string
		lineageTag: 171f388d-b31e-4173-a14c-059d215d66ec
		summarizeBy: none
		sourceColumn: Login

		annotation SummarizationSetBy = Automatic

	column Pergunta
		dataType: string
		lineageTag: 5309752d-92fb-4e5c-91b8-6b2efbfe05ac
		summarizeBy: none
		sourceColumn: Pergunta

		annotation SummarizationSetBy = Automatic

	column 'Resposta - Nota'
		dataType: int64
		formatString: 0
		lineageTag: 650fc123-885e-4945-9784-294fa7f82065
		summarizeBy: sum
		sourceColumn: Resposta - Nota

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: bbfc55a4-3ad0-4adb-a26d-5f5e226fd1f2
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column E-mail
		dataType: string
		lineageTag: 630f00d6-4ba3-4ca3-ac1c-33aef08f6191
		summarizeBy: none
		sourceColumn: E-mail

		annotation SummarizationSetBy = Automatic

	column Celular
		dataType: string
		lineageTag: fe604938-4f12-4794-9a0f-0fccd8fa135e
		summarizeBy: none
		sourceColumn: Celular

		annotation SummarizationSetBy = Automatic

	column Lição
		dataType: string
		lineageTag: 5ed6f20a-43a6-46da-a88b-8373241998e2
		summarizeBy: none
		sourceColumn: Lição

		annotation SummarizationSetBy = Automatic

	column 'Data de resposta'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 932808ab-5b34-4a5c-ba17-24ac25f54a4e
		summarizeBy: none
		sourceColumn: Data de resposta

		variation Variation
			isDefault
			relationship: a4af2aef-25af-40b0-81c4-513bbfb81c0d
			defaultHierarchy: LocalDateTable_0d86869e-1bb6-4282-8061-63201c339d59.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Departamento 1'
		dataType: string
		lineageTag: 4d0927ec-bfbe-43db-a266-03bdec1884a0
		summarizeBy: none
		sourceColumn: Departamento 1

		annotation SummarizationSetBy = Automatic

	column 'Departamento 2'
		dataType: string
		lineageTag: 7126f3f8-b32e-4ce0-a9d9-4c014131af09
		summarizeBy: none
		sourceColumn: Departamento 2

		annotation SummarizationSetBy = Automatic

	column Matrícula
		dataType: string
		lineageTag: 6e7f28f5-0b8d-4025-ad28-7501eae2775a
		summarizeBy: none
		sourceColumn: Matrícula

		annotation SummarizationSetBy = Automatic

	column Turma
		dataType: string
		lineageTag: 0b9dfc6d-6ccc-4df3-ac20-82021073bba4
		summarizeBy: none
		sourceColumn: Turma

		annotation SummarizationSetBy = Automatic

	column Campanha
		dataType: string
		lineageTag: fd1a014e-0bf3-4fd6-a151-f2fd0624e66f
		summarizeBy: none
		sourceColumn: Campanha

		annotation SummarizationSetBy = Automatic

	column 'Agrupamento de pergunta'
		dataType: string
		lineageTag: c2d3087b-eb05-4290-82a1-8a80568f5bfd
		summarizeBy: none
		sourceColumn: Agrupamento de pergunta

		annotation SummarizationSetBy = Automatic

	column Justificativa
		dataType: string
		lineageTag: 83804676-1278-49de-a59e-8383895e4618
		summarizeBy: none
		sourceColumn: Justificativa

		annotation SummarizationSetBy = Automatic

	column 'Resposta - Data'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 440abec4-8f22-47c2-961d-b59003363d87
		summarizeBy: none
		sourceColumn: Resposta - Data

		variation Variation
			isDefault
			relationship: 228b4107-a76a-4145-b119-f22afb9e113e
			defaultHierarchy: LocalDateTable_ec2b95e2-9e99-4a79-a6fc-6d5ebe0131d0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Instituição
		dataType: string
		lineageTag: 805493f6-40d2-41bd-9be8-cea94d32893c
		summarizeBy: none
		sourceColumn: Instituição

		annotation SummarizationSetBy = Automatic

	column 'Departamento 3'
		dataType: string
		lineageTag: eb382233-af14-4336-a01b-93836fe2344e
		summarizeBy: none
		sourceColumn: Departamento 3

		annotation SummarizationSetBy = Automatic

	column Personalizar
		dataType: string
		lineageTag: 5a0c74ad-e1cc-4b6f-98c6-61057f4fe9c6
		summarizeBy: none
		sourceColumn: Personalizar

		annotation SummarizationSetBy = Automatic

	column '% Aplicação as Aulas' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        DISTINCTCOUNT('dAvalieasAulas'[Login]),
			        'dAvalieasAulas'[Resposta - Data] <> DATE(1899, 01, 01),dAvalieasAulas[Instituição]="PM Campinas - FUMEC")
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			VAR percentual = 
			    DIVIDE(total,[ID Cadastrados])
			RETURN percentual 
			```
		lineageTag: 0a34f5ed-f9b9-4cbb-90ba-a11a64b800fc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nível 4'
		dataType: string
		lineageTag: cd01b271-c1eb-4488-b3d5-1387284fcc12
		summarizeBy: none
		sourceColumn: Nível 4

		annotation SummarizationSetBy = Automatic

	column 'Nível 0'
		dataType: string
		lineageTag: 1a2bf7b3-8d00-470d-ae69-680383ff5f6d
		summarizeBy: none
		sourceColumn: Nível 0

		annotation SummarizationSetBy = Automatic

	column 'Nível 1'
		dataType: string
		lineageTag: e13c4150-430f-49f9-a9f1-f9f50fad1d6c
		summarizeBy: none
		sourceColumn: Nível 1

		annotation SummarizationSetBy = Automatic

	column 'Nível 2'
		dataType: string
		lineageTag: add6e6d1-9385-48a7-8461-101dfcad2ab3
		summarizeBy: none
		sourceColumn: Nível 2

		annotation SummarizationSetBy = Automatic

	column 'Nível 3'
		dataType: string
		lineageTag: 6e3647c1-b6b8-4608-b4af-69f78ab2232d
		summarizeBy: none
		sourceColumn: Nível 3

		annotation SummarizationSetBy = Automatic

	partition dAvalieasAulas-775e107c-042d-4330-8de7-bc60d5461604 = m
		mode: import
		queryGroup: Relatórios
		source =
				let
				    timestamp_now = DateTime.From(DateTimeZone.ToText(DateTimeZone.UtcNow())) - #duration(0, 3, 0, 0),
				    #"Data Extraída" = Date.From(timestamp_now),
				    date_text = Date.ToText(#"Data Extraída", "yyyy-MM-dd"),
				    string = date_text & KEY,
				    senha_codificada = codificacao(string),
				    Fonte = Json.Document(Web.Contents(LINK_FUNCAO, [Query=[senha=senha_codificada]])),
				    link = Fonte[link_avalie_aulas],
				    path = Text.Split(link, "/"){5},
				    arquivo = Csv.Document(Web.Contents(CAMINHO_BUCKET & "/avalie_aulas", [RelativePath=path])),
				    arquivo_cabecalho = Table.PromoteHeaders(arquivo, [PromoteAllScalars=true]),
				    #"Valor Substituído" = Table.ReplaceValue(arquivo_cabecalho,"Formato: dd/mm/aaaa","",Replacer.ReplaceText,{"Pergunta"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","Exemplo: 02/03/2022","",Replacer.ReplaceText,{"Pergunta"}),
				    #"Texto Aparado" = Table.TransformColumns(#"Valor Substituído1",{{"Pergunta", Text.Trim, type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Texto Aparado",{""}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas",{{"Nível 0", "Instituição"}, {"Nível 1", "Departamento 1"}, {"Nível 2", "Departamento 2"}, {"Nível 3", "Departamento 3"}}),
				    #"Coluna Duplicada" = Table.DuplicateColumn(#"Colunas Renomeadas", "Resposta", "Resposta - Copiar"),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Coluna Duplicada",{{"Resposta", "Resposta - Data"}, {"Resposta - Copiar", "Resposta - Nota"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Resposta - Nota", Int64.Type}}),
				    #"Erros Substituídos" = Table.ReplaceErrorValues(#"Tipo Alterado", {{"Resposta - Nota", 1000}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Erros Substituídos",{{"Resposta - Data", type date}}),
				    #"Erros Substituídos1" = Table.ReplaceErrorValues(#"Tipo Alterado1", {{"Resposta - Data", #date(1899, 1, 1)}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Erros Substituídos1",{{"Data de resposta", type date}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado2", each Text.Contains([Turma], "2024")),
				    #"Personalização Adicionada" = Table.AddColumn(#"Linhas Filtradas1", "Personalizar", each "clássico"),
				    #"Consulta Acrescentada" = Table.Combine({#"Personalização Adicionada", dAvalieasAulasPVML}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Consulta Acrescentada",{{"Personalizar", type text}}),
				    #"Consulta Acrescentada1" = Table.Combine({#"Tipo Alterado3", dAvalieasAulasCreches}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Consulta Acrescentada1", each Text.Contains([Turma], "2024") and not Text.Contains([Turma], "Maceió"))
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

