table dAvalieTutoria
	lineageTag: 077d5875-faf7-4d2a-8e64-e0f39e21a403

	column Nome
		dataType: string
		lineageTag: 3446d86c-3463-4cd7-af73-62dbf357d107
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Login
		dataType: string
		lineageTag: 9df870fe-6324-49b4-9c5b-19313521c5bb
		summarizeBy: none
		sourceColumn: Login

		annotation SummarizationSetBy = Automatic

	column Lição
		dataType: string
		lineageTag: 1db640cb-1348-416f-aa70-ebd70cd50ff1
		summarizeBy: none
		sourceColumn: Lição

		annotation SummarizationSetBy = Automatic

	column Pergunta
		dataType: string
		lineageTag: 9072ca68-4467-42f8-b83d-b523ce096f82
		summarizeBy: none
		sourceColumn: Pergunta

		annotation SummarizationSetBy = Automatic

	column Resposta
		dataType: int64
		formatString: 0
		lineageTag: c975dc72-3a9a-4c3e-8974-c2f2a8893c7c
		summarizeBy: sum
		sourceColumn: Resposta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column CPF
		dataType: string
		lineageTag: 28b5759d-255e-4f94-8480-37d02b8833f8
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column E-mail
		dataType: string
		lineageTag: 955b6e29-5190-43e2-a616-34f8f7456608
		summarizeBy: none
		sourceColumn: E-mail

		annotation SummarizationSetBy = Automatic

	column Celular
		dataType: int64
		formatString: 0
		lineageTag: 7ddc814b-7263-4963-81b9-fe537e055d62
		summarizeBy: sum
		sourceColumn: Celular

		annotation SummarizationSetBy = Automatic

	column Matrícula
		dataType: string
		lineageTag: c61aa291-7424-4fe3-af52-e4ce6cafde76
		summarizeBy: none
		sourceColumn: Matrícula

		annotation SummarizationSetBy = Automatic

	column Turma
		dataType: string
		lineageTag: a81214c0-0670-4074-b213-df582c3f49af
		summarizeBy: none
		sourceColumn: Turma

		annotation SummarizationSetBy = Automatic

	column Justificativa
		dataType: string
		lineageTag: 2206c4bf-212b-4be0-93b6-a1948ff21baa
		summarizeBy: none
		sourceColumn: Justificativa

		annotation SummarizationSetBy = Automatic

	column 'Data de resposta'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 31294646-a9e9-4d25-a29b-f176b8394d2e
		summarizeBy: none
		sourceColumn: Data de resposta

		variation Variation
			isDefault
			relationship: ceee510d-9495-42e3-86cb-3f8f0a3bb98a
			defaultHierarchy: LocalDateTable_90c52f0c-a622-4757-bca0-c1a94e2f58ba.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Nível 1'
		dataType: string
		lineageTag: 7187606f-6a7b-4151-b80a-4ad934912812
		summarizeBy: none
		sourceColumn: Nível 1

		annotation SummarizationSetBy = Automatic

	column Campanha
		dataType: string
		lineageTag: 93f672cd-4e59-49a5-9215-223a84254fa6
		summarizeBy: none
		sourceColumn: Campanha

		annotation SummarizationSetBy = Automatic

	column 'Agrupamento de pergunta'
		dataType: string
		lineageTag: bd116c95-493f-4987-a654-71c26f248616
		summarizeBy: none
		sourceColumn: Agrupamento de pergunta

		annotation SummarizationSetBy = Automatic

	column 'Nível 0'
		dataType: string
		lineageTag: 53eb02a0-c0ca-4cda-89eb-4f7709aeca35
		summarizeBy: none
		sourceColumn: Nível 0

		annotation SummarizationSetBy = Automatic

	column 'Tutoria.1'
		dataType: string
		lineageTag: b010ec9d-a889-4a3e-9d6e-3d7d7564a457
		summarizeBy: none
		sourceColumn: Tutoria.1

		annotation SummarizationSetBy = Automatic

	column 'Nível 2'
		dataType: string
		lineageTag: 8f496d49-2664-4216-b09c-a8598007364b
		summarizeBy: none
		sourceColumn: Nível 2

		annotation SummarizationSetBy = Automatic

	column 'Nível 3'
		dataType: string
		lineageTag: 76b7b8d0-f75f-423d-8031-89549527a51b
		summarizeBy: none
		sourceColumn: Nível 3

		annotation SummarizationSetBy = Automatic

	column 'Nível 4'
		dataType: string
		lineageTag: 1b5777b4-73f1-4d0c-b50d-44b0b7546fc5
		summarizeBy: none
		sourceColumn: Nível 4

		annotation SummarizationSetBy = Automatic

	partition dAvalieTutoria-585109b8-f128-44b0-9233-8ebb63b5d301 = m
		mode: import
		queryGroup: Relatórios
		source =
				let
				    timestamp_now = DateTime.From(DateTimeZone.ToText(DateTimeZone.UtcNow())) - #duration(0, 3, 0, 0),
				    #"Data Extraída" = Date.From(timestamp_now),
				    date_text = Date.ToText(#"Data Extraída", "yyyy-MM-dd"),
				    string = date_text & KEY,
				    senha_codificada = codificacao(string),
				    Fonte = Json.Document(Web.Contents(LINK_FUNCAO, [Query=[senha=senha_codificada]])),
				    link = Fonte[link_avalie_tutoria],
				    path = Text.Split(link, "/"){5},
				    arquivo = Csv.Document(Web.Contents(CAMINHO_BUCKET & "/avalie_tutoria", [RelativePath=path])),
				    arquivo_cabecalho = Table.PromoteHeaders(arquivo, [PromoteAllScalars=true]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(arquivo_cabecalho, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"0", Int64.Type}, {"Nome", type text}, {"CPF", type text}, {"Login", type text}, {"E-mail", type text}, {"Celular", Int64.Type}, {"Matrícula", type text}, {"Lição", type text}, {"Turma", type text}, {"Campanha", type text}, {"Agrupamento de pergunta", type text}, {"Pergunta", type text}, {"Resposta", Int64.Type}, {"Justificativa", type text}, {"Data de resposta", type date}, {"Nível 0", type text}, {"Nível 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"0"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Removidas","Em uma escala de 0 a 10 como você avalia o formador responsável pela Tutoria.","Formador",Replacer.ReplaceText,{"Pergunta"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","Em uma escala de 0 a 10, como você avalia a Tutoria ocorrida?","Tutoria",Replacer.ReplaceText,{"Pergunta"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Valor Substituído1", each [Login] <> ""),
				    #"Coluna Duplicada" = Table.DuplicateColumn(#"Linhas Filtradas", "Lição", "Lição - Copiar"),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Coluna Duplicada",{{"Lição - Copiar", "Tutoria"}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Colunas Renomeadas1", "Tutoria", Splitter.SplitTextByPositions({0, 17}, false), {"Tutoria.1", "Tutoria.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Tutoria.1", type text}, {"Tutoria.2", type text}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Tipo Alterado1",{"Tutoria.2"})
				in
				    #"Colunas Removidas1"

	annotation PBI_ResultType = Table

