table dEntregaMateriaisPartes
	lineageTag: 713218b2-112a-4e04-84c7-80298b731ee2

	column 'Tipo de Pergunta'
		dataType: string
		lineageTag: faaa97d1-662d-47fa-b79f-18a9ac0bbe74
		summarizeBy: none
		sourceColumn: Tipo de Pergunta

		annotation SummarizationSetBy = Automatic

	column Resposta2 = ```
			
			VAR Tipo_Pergunta = dEntregaMateriaisPartes[Tipo de Pergunta]
			        
			VAR Resposta = dEntregaMateriaisPartes[Resposta]
			
			VAR Resposta2 = 
			        SWITCH(
			            TRUE(),
			            Resposta="não encontrado",dEntregaMateriaisPartes[Resposta],
			            Tipo_Pergunta="Escola",Resposta,
			            Tipo_Pergunta="Professor"&&Resposta="Sim, tenho um só pra mim","Sim",
			            Tipo_Pergunta="Professor"&&Resposta="Sim, tenho um de uso compartilhado","Sim",
			            Tipo_Pergunta="Professor"&&Resposta="Não, a escola recebeu e ainda não entregou pra mim","Não",
			            Tipo_Pergunta="Professor"&&Resposta="Não, a escola não recebeu esse material","Não",
			            Tipo_Pergunta="Aluno"&&Resposta="Sim, todos os alunos possuem","Sim",
			            Tipo_Pergunta="Aluno"&&Resposta="Sim, parte dos alunos possui pois não temos mais materiais para entregar","Sim",
			            Tipo_Pergunta="Aluno"&&Resposta="Sim, parte dos alunos possui pois, apesar de termos os materiais, ainda não entregamos para todos os alunos","Sim",
			            Tipo_Pergunta="Aluno"&&Resposta="Não, a escola recebeu e ainda não entregou","Não",
			            Tipo_Pergunta="Aluno"&&Resposta="Não, a escola não recebeu esse material","Não"
			        )
			Return Resposta2            
			```
		lineageTag: 130d06ba-319c-424c-a823-a0e680a552d7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Respondeu a primeira vez?' = ```
			
			VAR Resposta = 
			        LOOKUPVALUE(
			                    dEntregaMateriais[Resposta Completa],
			                    dEntregaMateriais[Login],dEntregaMateriaisPartes[Login],
			                    dEntregaMateriais[Tipo de Pergunta],dEntregaMateriaisPartes[Tipo de Pergunta],
			                    "não encontrou"
			        )
			
			VAR respondeu = 
			        IF(Resposta="não encontrou",FALSE,TRUE)
			
			Return respondeu
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 149c76f9-5510-4344-ba65-e934250b37a1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Usuário
		dataType: string
		lineageTag: 7c1697f4-6619-4991-a5e6-f7c75ee17cf2
		summarizeBy: none
		sourceColumn: Usuário

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: 944940a1-ff85-4cd4-b50c-a5abe2d15c9e
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column Login
		dataType: string
		lineageTag: d45e8698-4f22-4a47-8ebc-d238601f3cb2
		summarizeBy: none
		sourceColumn: Login

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 32fb0764-e13f-4f7b-b422-060e6612b051
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Perfil
		dataType: string
		lineageTag: 01ab837e-ca2b-4eec-b5b9-6e1b233ebb28
		summarizeBy: none
		sourceColumn: Perfil

		annotation SummarizationSetBy = Automatic

	column Empresa
		dataType: string
		lineageTag: 49544281-0ced-4349-a1e3-41a895e94d0f
		summarizeBy: none
		sourceColumn: Empresa

		annotation SummarizationSetBy = Automatic

	column 'Departamento 1'
		dataType: string
		lineageTag: 18f325c6-c874-44b8-bb13-381ee32f289b
		summarizeBy: none
		sourceColumn: Departamento 1

		annotation SummarizationSetBy = Automatic

	column 'Departamento 2'
		dataType: string
		lineageTag: 408e5a0a-355b-49e7-8c3a-406601db8c13
		summarizeBy: none
		sourceColumn: Departamento 2

		annotation SummarizationSetBy = Automatic

	column 'Departamento 3'
		dataType: string
		lineageTag: 910db601-fc37-4ecc-83ed-95b6ab72be99
		summarizeBy: none
		sourceColumn: Departamento 3

		annotation SummarizationSetBy = Automatic

	column Pergunta
		dataType: string
		lineageTag: 5685a099-71cf-4155-97e6-e1a5c5c05d75
		summarizeBy: none
		sourceColumn: Pergunta

		annotation SummarizationSetBy = Automatic

	column Resposta
		dataType: string
		lineageTag: cc48eda9-53f5-491b-a11f-5d3fd06725c4
		summarizeBy: none
		sourceColumn: Resposta

		annotation SummarizationSetBy = Automatic

	column 'Resposta Completa' = ""
		lineageTag: 73c1503e-00d1-416a-8bbe-f03f4cb0e709
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Departamento 4'
		dataType: string
		lineageTag: 42787c29-a426-419b-a3c6-bc44874d13eb
		summarizeBy: none
		sourceColumn: Departamento 4

		annotation SummarizationSetBy = Automatic

	partition dEntregaMateriaisPartes = m
		mode: import
		queryGroup: Relatórios
		source =
				let
				    timestamp_now = DateTime.From(DateTimeZone.ToText(DateTimeZone.UtcNow())) - #duration(0, 3, 0, 0),
				    #"Data Extraída" = Date.From(timestamp_now),
				    date_text = Date.ToText(#"Data Extraída", "yyyy-MM-dd"),
				    string = date_text & KEY,
				    senha_codificada = codificacao(string),
				    Fonte = Json.Document(Web.Contents(LINK_FUNCAO, [Query=[senha=senha_codificada]])),
				    link = Fonte[link_materiais_partes2],
				    path = Text.Split(link, "/"){5},
				    arquivo = Csv.Document(Web.Contents(CAMINHO_BUCKET & "/materiais", [RelativePath=path])),
				    arquivo_cabecalho = Table.PromoteHeaders(arquivo, [PromoteAllScalars=true]),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(arquivo_cabecalho, "Tipo de Pergunta", each if [Pergunta] = "Considerando que você respondeu anteriormente que o <b>Laboratório de Jogos não estava disponível para utilização em sala de aula</b>, gostaríamos de saber: <br><br><b>Agora o Laboratório de Jogos está disponível?</b>" then "Escola" else if [Pergunta] = "Considerando que você respondeu anteriormente que <b>não tinha recebido o Livro do Professor</b>, gostaríamos de saber: <br><br><b>Agora você já tem acesso a esse material?</b>" then "Professor" else if [Pergunta] = "Considerando que você respondeu anteriormente que os estudantes, na sua totalidade ou em parte, <b>não tinham recebido o Livro do Aluno</b>, gostaríamos de saber: <br><br><b>O material já foi distribuído para os estudantes?</b>" then "Aluno" else "Erro"),
				    #"Linhas Filtradas" = Table.SelectRows(#"Coluna Condicional Adicionada", each true),
				    #"Personalização Adicionada" = Table.AddColumn(#"Linhas Filtradas", "Departamento 4", each "")
				in
				    #"Personalização Adicionada"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

