table dMHS
	lineageTag: 2d666d1f-fc0d-4789-bea0-45b45a93c1fe

	column Usuário
		dataType: string
		lineageTag: 2f31d239-a9e3-4d01-ba85-3ea507f11b01
		summarizeBy: none
		sourceColumn: Usuário

		annotation SummarizationSetBy = Automatic

	column Login
		dataType: string
		lineageTag: 1cbd1081-80ba-4b1d-926b-0dd0382800df
		summarizeBy: none
		sourceColumn: Login

		annotation SummarizationSetBy = Automatic

	column Pergunta
		dataType: string
		lineageTag: 48b0fe98-ed62-4b70-87c4-979defef3e38
		summarizeBy: none
		sourceColumn: Pergunta

		annotation SummarizationSetBy = Automatic

	column Resposta
		dataType: string
		lineageTag: 56a49619-e4d8-4cec-b2c6-e1120f4fa8d2
		summarizeBy: none
		sourceColumn: Resposta

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: c781019f-9c5f-4a2d-8e49-5cf67471e963
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: a149e7a3-696b-42cf-bd12-74495b5d391b
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Perfil
		dataType: string
		lineageTag: d9bfd9aa-ae00-4fb2-83df-331fa1494ebf
		summarizeBy: none
		sourceColumn: Perfil

		annotation SummarizationSetBy = Automatic

	column 'Departamento 1'
		dataType: string
		lineageTag: b7269b71-6c61-4cf8-b1fb-d06305011099
		summarizeBy: none
		sourceColumn: Departamento 1

		annotation SummarizationSetBy = Automatic

	column 'Departamento 2'
		dataType: string
		lineageTag: b660ed27-ee3f-426e-83ab-39a652676f07
		summarizeBy: none
		sourceColumn: Departamento 2

		annotation SummarizationSetBy = Automatic

	column Empresa
		dataType: string
		lineageTag: d5e1dd4b-2325-4d45-b026-a5cfb5dd6e5d
		summarizeBy: none
		sourceColumn: Empresa

		annotation SummarizationSetBy = Automatic

	column 'Departamento 3'
		dataType: string
		lineageTag: 2c4adbc2-6e58-4116-90ed-ffea3557a11d
		summarizeBy: none
		sourceColumn: Departamento 3

		annotation SummarizationSetBy = Automatic

	column MHS
		dataType: string
		lineageTag: 1a5e37a7-ddd8-4beb-8e16-42f172ce4b5e
		summarizeBy: none
		sourceColumn: MHS

		annotation SummarizationSetBy = Automatic

	column 'Departamento 4'
		dataType: string
		lineageTag: ab0cc92c-c81e-4f0f-a06c-ea7da3d05afd
		summarizeBy: none
		sourceColumn: Departamento 4

		annotation SummarizationSetBy = Automatic

	partition dMHS-9008c17a-ca6e-45a2-870a-de6d6c2c0342 = m
		mode: import
		queryGroup: Relatórios
		source =
				let
				    timestamp_now = DateTime.From(DateTimeZone.ToText(DateTimeZone.UtcNow())) - #duration(0, 3, 0, 0),
				    #"Data Extraída" = Date.From(timestamp_now),
				    date_text = Date.ToText(#"Data Extraída", "yyyy-MM-dd"),
				    string = date_text & KEY,
				    senha_codificada = codificacao(string),
				    Fonte = Json.Document(Web.Contents(LINK_FUNCAO, [Query=[senha=senha_codificada]])),
				    link = Fonte[link_MHS],
				    path = Text.Split(link, "/"){5},
				    arquivo = Csv.Document(Web.Contents(CAMINHO_BUCKET & "/MHS", [RelativePath=path])),
				    arquivo_cabecalho = Table.PromoteHeaders(arquivo, [PromoteAllScalars=true]),
				    #"Valor Substituído" = Table.ReplaceValue(arquivo_cabecalho,"1","MHS 1",Replacer.ReplaceText,{"MHS"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","2","MHS 2",Replacer.ReplaceText,{"MHS"})
				in
				    #"Valor Substituído1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

