table dPercepcaoprofessores
	lineageTag: 54484ecc-8904-47ff-acfa-3a6e9872f209

	measure '% Gestão das Emoções' = ```
			
			VAR Pergunta = "O Método Semáforo (Seu Máforo) tem ajudado os estudantes/crianças a gerenciar melhor as emoções."
			
			VAR QuantidadeConcordo = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]="Concordo totalmente" || dPercepcaoprofessores[Resposta]="Concordo parcialmente"  
			    )
			
			RETURN
			    DIVIDE(QuantidadeConcordo, [Quantidade Gestão das Emoções])
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 95afd8eb-c1b9-4950-a01b-689a4b3907e7

	measure 'Quantidade Gestão das Emoções' = ```
			
			VAR Pergunta = "O Método Semáforo (Seu Máforo) tem ajudado os estudantes/crianças a gerenciar melhor as emoções."
			
			VAR QuantidadeRespostas = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]<>"Não sei responder"
			    )
			    
			RETURN
			    QuantidadeRespostas
			```
		formatString: 0
		lineageTag: 6cf0d073-dbee-4f3a-9079-6a4a189ea615

	measure 'Quantidade Resolução de Problemas' = ```
			
			VAR Pergunta = "As ferramentas da metodologia (métodos e estratégias) e o raciocínio lógico envolvidos nas situações com os jogos têm contribuído para que os estudantes/crianças desenvolvam habilidades relacionadas à resolução de problemas."
			
			VAR QuantidadeRespostas = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]<>"Não sei responder"
			    )
			    
			RETURN
			    QuantidadeRespostas
			```
		formatString: 0
		lineageTag: bfdad651-67c7-491a-b346-ec2325162b6f

	measure 'Quantidade Clima Escolar' = ```
			
			VAR Pergunta = "O respeito mútuo e as demais habilidades envolvidas nos momentos de vivência com os jogos da metodologia favorecem momentos de interação entre os estudantes/crianças e têm ajudado na redução dos desentendimentos e nos casos de bullying."
			
			VAR QuantidadeRespostas = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]<>"Não sei responder"
			    )
			    
			RETURN
			    QuantidadeRespostas
			```
		formatString: 0
		lineageTag: 91db10da-c2dc-4abc-a8c6-1bdffaad58f9

	measure 'Quantidade Foco e Atenção' = ```
			
			VAR Pergunta = "Os recursos lúdicos da metodologia Mind Lab/Programa MenteInovadora promovem o engajamento dos estudantes/crianças, favorecendo para que eles/elas tenham maior atenção e foco nas atividades."
			
			VAR QuantidadeRespostas = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]<>"Não sei responder"
			    )
			    
			RETURN
			    QuantidadeRespostas
			```
		formatString: 0
		lineageTag: 387236db-06d5-4860-b591-82f482675ceb

	measure 'Quantidade Tomada de Decisões' = ```
			
			VAR Pergunta = "A metodologia Mind Lab/Programa MenteInovadora tem favorecido o desenvolvimento das habilidades socioemocionais dos estudantes/crianças, o que tem ajudado para que eles/elas se sintam mais confiantes para a tomada de decisões."
			
			VAR QuantidadeRespostas = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]<>"Não sei responder"
			    )
			    
			RETURN
			    QuantidadeRespostas
			```
		formatString: 0
		lineageTag: 8d01cfe8-2aec-45c5-b6fc-6919fdcd889e

	measure 'Quantidade Trabalho em Equipe' = ```
			
			VAR Pergunta = "O Método Aves Migratórias (Equipe Tripe) tem ajudado os estudantes/crianças a ter uma postura mais colaborativa nas atividades em grupo."
			
			VAR QuantidadeRespostas = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]<>"Não sei responder"
			    )
			    
			RETURN
			    QuantidadeRespostas
			```
		formatString: 0
		lineageTag: 230e72bb-68f5-42bf-9b37-d6d5266cb9aa

	measure '% Clima Escolar' = ```
			
			VAR Pergunta = "O respeito mútuo e as demais habilidades envolvidas nos momentos de vivência com os jogos da metodologia favorecem momentos de interação entre os estudantes/crianças e têm ajudado na redução dos desentendimentos e nos casos de bullying."
			
			VAR QuantidadeConcordo = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]="Concordo totalmente" || dPercepcaoprofessores[Resposta]="Concordo parcialmente"  
			    )
			
			RETURN
			    DIVIDE(QuantidadeConcordo, [Quantidade Clima Escolar])
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bac44757-3796-4e7a-beb2-5b62a3733a71

	measure '% Foco e Atenção' = ```
			
			VAR Pergunta = "Os recursos lúdicos da metodologia Mind Lab/Programa MenteInovadora promovem o engajamento dos estudantes/crianças, favorecendo para que eles/elas tenham maior atenção e foco nas atividades."
			
			VAR QuantidadeConcordo = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]="Concordo totalmente" || dPercepcaoprofessores[Resposta]="Concordo parcialmente"  
			    )
			
			RETURN
			    DIVIDE(QuantidadeConcordo, [Quantidade Foco e Atenção])
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8f4b5bb8-3791-4d37-933a-10ecc0cdec6a

	measure '% Resolução de Problemas' = ```
			
			VAR Pergunta = "As ferramentas da metodologia (métodos e estratégias) e o raciocínio lógico envolvidos nas situações com os jogos têm contribuído para que os estudantes/crianças desenvolvam habilidades relacionadas à resolução de problemas."
			
			VAR QuantidadeConcordo = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]="Concordo totalmente" || dPercepcaoprofessores[Resposta]="Concordo parcialmente"  
			    )
			
			RETURN
			    DIVIDE(QuantidadeConcordo, [Quantidade Resolução de Problemas])
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6fcb707e-7f33-4edf-a0eb-a9cfe2f16226

	measure '% Tomada de Decisões' = ```
			
			VAR Pergunta = "A metodologia Mind Lab/Programa MenteInovadora tem favorecido o desenvolvimento das habilidades socioemocionais dos estudantes/crianças, o que tem ajudado para que eles/elas se sintam mais confiantes para a tomada de decisões."
			
			VAR QuantidadeConcordo = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]="Concordo totalmente" || dPercepcaoprofessores[Resposta]="Concordo parcialmente"  
			    )
			
			RETURN
			    DIVIDE(QuantidadeConcordo, [Quantidade Tomada de Decisões])
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 792ec021-aa85-4069-be6e-b688fbc52232

	measure '% Trabalho em Equipe' = ```
			
			VAR Pergunta = "O Método Aves Migratórias (Equipe Tripe) tem ajudado os estudantes/crianças a ter uma postura mais colaborativa nas atividades em grupo."
			
			VAR QuantidadeConcordo = 
			    CALCULATE(
			        COUNTROWS(dPercepcaoprofessores)
			        , dPercepcaoprofessores[Pergunta]= Pergunta
			        , dPercepcaoprofessores[Resposta]="Concordo totalmente" || dPercepcaoprofessores[Resposta]="Concordo parcialmente"  
			    )
			
			RETURN
			    DIVIDE(QuantidadeConcordo, [Quantidade Trabalho em Equipe])
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d9a2d7f5-4c49-44c5-9f9d-b791128ed4b3

	column Usuário
		dataType: string
		lineageTag: 39596de8-6d67-4700-aab6-dad6534d1689
		summarizeBy: none
		sourceColumn: Usuário

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: d333cfe2-ee9d-4ebd-9d51-ef8c40c23a12
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column Login
		dataType: string
		lineageTag: 5e8febd4-48e4-406f-8554-ff4bce5c484c
		summarizeBy: none
		sourceColumn: Login

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 8548f586-d929-4088-a3db-e81080a2dd76
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Perfil
		dataType: string
		lineageTag: d58b6a02-2149-4ab9-a392-521f74a0cd1c
		summarizeBy: none
		sourceColumn: Perfil

		annotation SummarizationSetBy = Automatic

	column Empresa
		dataType: string
		lineageTag: 015904ff-7bd4-4cad-83a9-1a85387c5583
		summarizeBy: none
		sourceColumn: Empresa

		annotation SummarizationSetBy = Automatic

	column 'Departamento 1'
		dataType: string
		lineageTag: 57eb7733-e811-4aec-97c4-1efc719321fd
		summarizeBy: none
		sourceColumn: Departamento 1

		annotation SummarizationSetBy = Automatic

	column 'Departamento 2'
		dataType: string
		lineageTag: 5f0ec37f-048a-444d-b4c9-e1f20ef3a334
		summarizeBy: none
		sourceColumn: Departamento 2

		annotation SummarizationSetBy = Automatic

	column 'Departamento 3'
		dataType: string
		lineageTag: 86e82edd-2112-4c30-ada5-7c92251d6648
		summarizeBy: none
		sourceColumn: Departamento 3

		annotation SummarizationSetBy = Automatic

	column 'Departamento 4'
		dataType: string
		lineageTag: 4c985a8b-6d41-4a7d-bd3e-b4700dadccc0
		summarizeBy: none
		sourceColumn: Departamento 4

		annotation SummarizationSetBy = Automatic

	column Pergunta
		dataType: string
		lineageTag: 21a8e307-0f1a-4290-80a1-bd9b4417d691
		summarizeBy: none
		sourceColumn: Pergunta

		annotation SummarizationSetBy = Automatic

	column Resposta
		dataType: string
		lineageTag: 3e92051e-08e9-4456-abe1-c26be1c57558
		summarizeBy: none
		sourceColumn: Resposta

		annotation SummarizationSetBy = Automatic

	partition dPercepcaoprofessores = m
		mode: import
		queryGroup: Relatórios
		source =
				let
				    timestamp_now = DateTime.From(DateTimeZone.ToText(DateTimeZone.UtcNow())) - #duration(0, 3, 0, 0),
				    #"Data Extraída" = Date.From(timestamp_now),
				    date_text = Date.ToText(#"Data Extraída", "yyyy-MM-dd"),
				    string = date_text & KEY,
				    senha_codificada = codificacao(string),
				    Fonte = Json.Document(Web.Contents(LINK_FUNCAO, [Query=[senha=senha_codificada]])),
				    link = Fonte[link_percepcao_professores],
				    path = Text.Split(link, "/"){5},
				    arquivo = Csv.Document(Web.Contents(CAMINHO_BUCKET & "/percepcao_professores", [RelativePath=path])),
				    arquivo_cabecalho = Table.PromoteHeaders(arquivo, [PromoteAllScalars=true])
				in
				    arquivo_cabecalho

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

