table dReceita
	excludeFromModelRefresh
	lineageTag: 054eaa56-c1f0-437d-b2a3-834e3c2241d2

	measure 'Valor da receita' = CALCULATE(SUM(dReceita[Valor]),ALL(dRelatoriodeUsuarios[Função]))
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 8707f887-8a20-4bd9-9b5e-e97b3f40073e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Modalidade ok' = CALCULATE(FIRSTNONBLANK (dReceita[Modalidade],TRUE()),ALL(dRelatoriodeUsuarios[Função]))
		lineageTag: a6c52fec-ff9f-4aff-9aae-f929fcdf435e

	column Instituição
		dataType: string
		lineageTag: da71f258-f3be-41ab-9512-fedec392c759
		summarizeBy: none
		sourceColumn: Instituição

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8b917727-d0f5-4a16-99f5-1124b0bee918
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = User

	column %
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6f58e4ed-0bbe-4886-a4a9-e6fb6f1c7f4f
		summarizeBy: sum
		sourceColumn: %

		annotation SummarizationSetBy = User

	column Modalidade
		dataType: string
		lineageTag: 009256cb-a581-4322-b315-c73a5a1de0a0
		summarizeBy: none
		sourceColumn: Modalidade

		annotation SummarizationSetBy = Automatic

	column 'Previsão de Pagamento'
		dataType: string
		lineageTag: 883214f2-1dd2-4e29-822c-016d0f5cb045
		summarizeBy: none
		sourceColumn: Previsão de Pagamento

		annotation SummarizationSetBy = Automatic

	column Distribuição
		dataType: string
		lineageTag: e7e90b07-89c5-446c-acf3-3c1b77c7e2e6
		summarizeBy: none
		sourceColumn: Distribuição

		annotation SummarizationSetBy = Automatic

	column 'Previsão de Entrega'
		dataType: string
		lineageTag: 9013d3cb-da93-490a-a4f0-3ca795ba9226
		summarizeBy: none
		sourceColumn: Previsão de Entrega

		annotation SummarizationSetBy = Automatic

	column 'Entrega nas Escolas?'
		dataType: string
		lineageTag: b5cdbbc1-8853-4095-952a-62bc84737ff1
		summarizeBy: none
		sourceColumn: Entrega nas Escolas?

		annotation SummarizationSetBy = Automatic

	column 'Cliente aparece na planilha comercial?'
		dataType: string
		lineageTag: 1b8ada89-8ede-42b4-9622-04f459c8a388
		summarizeBy: none
		sourceColumn: Cliente aparece na planilha comercial?

		annotation SummarizationSetBy = Automatic

	column 'Quantidade Total'
		dataType: int64
		formatString: 0
		lineageTag: 829539f3-99a4-4788-9c80-21db80286137
		summarizeBy: none
		sourceColumn: Quantidade Total

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Quantidade Entregue'
		dataType: int64
		formatString: 0
		lineageTag: c485cef8-1577-4f5f-9d27-8acd41f727d3
		summarizeBy: none
		sourceColumn: Quantidade Entregue

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Quantidade em branco'
		dataType: int64
		formatString: 0
		lineageTag: b9c517a5-a0d5-46e1-9371-5b973b88f117
		summarizeBy: none
		sourceColumn: Quantidade em branco

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition dReceita-7a93009d-7724-4e9c-a736-7495fc98cf4b = m
		mode: import
		queryGroup: 'Consultas sheets'
		source =
				let
				    Fonte = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/16E32t-YvoFjvkkiW2fxw3leh6z-98SiviXJNqoqGHYU/edit#gid=1079823787"),
				    #"Clientes Publico_Sheet" = Fonte{[name="Dados hujidjidjijkokosk",ItemKind="Table"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Clientes Publico_Sheet", [PromoteAllScalars=true]),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Cabeçalhos Promovidos", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas em Branco Removidas",{{"%", Percentage.Type}, {"Valor", Currency.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

