table dRelatoriodeUsuarios
	lineageTag: b2b5cc3b-795f-4f72-a559-e9893fc73de5

	column Nome
		dataType: string
		lineageTag: a0129819-e352-4b30-ad5a-775cd497613a
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Login
		dataType: string
		lineageTag: 7103b336-384b-4d9a-ae81-138af6821d6b
		summarizeBy: none
		sourceColumn: Login

		annotation SummarizationSetBy = Automatic

	column Função
		dataType: string
		lineageTag: 4b423e8d-3c8b-45c2-b6f0-553da4e3da96
		summarizeBy: none
		sourceColumn: Função

		annotation SummarizationSetBy = Automatic

	column Mesclado
		dataType: string
		lineageTag: c7e29ba9-8e9f-4b09-b2e9-53131499c69c
		summarizeBy: none
		sourceColumn: Mesclado

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 6268fa4d-3b22-4fc2-8a3e-0b9d39bff893
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: 61ff2aac-9547-43de-9651-cb79f6c0015d
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column Cargo
		dataType: string
		lineageTag: 738a9d62-b507-457b-b13b-e867741dc5b6
		summarizeBy: none
		sourceColumn: Cargo

		annotation SummarizationSetBy = Automatic

	column 'Data de admissão'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 728e349b-3f5e-4d7a-951d-cb7865394230
		summarizeBy: none
		sourceColumn: Data de admissão

		variation Variation
			isDefault
			relationship: 0ad675f5-90c0-42c9-a173-13f20f91f8ef
			defaultHierarchy: LocalDateTable_1c017a63-aef1-432c-aca9-57a826f70adf.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Último Login'
		dataType: dateTime
		formatString: General Date
		lineageTag: df6ac357-f38a-4794-8e9f-91e1cb0aff91
		summarizeBy: none
		sourceColumn: Último Login

		variation Variation
			isDefault
			relationship: 611aee41-8dc7-43cd-86e3-578e4da05728
			defaultHierarchy: LocalDateTable_05c5b471-c756-4520-aba3-3b76e2880cf2.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Departamento 1'
		dataType: string
		lineageTag: e58f6a8c-be1e-44e8-ba3f-7c931704402a
		summarizeBy: none
		sourceColumn: Departamento 1

		annotation SummarizationSetBy = Automatic

	column 'Departamento 2'
		dataType: string
		lineageTag: f3811883-0652-4d46-b6bc-5c29fd82d063
		summarizeBy: none
		sourceColumn: Departamento 2

		annotation SummarizationSetBy = Automatic

	column 'Ano Escolar' = ```
			
			    SWITCH(
			        TRIM(dRelatoriodeUsuarios[Função.2]),
			        "Educação Infantil - Creche - 1 ano", "EI Creche",
			        "Educação Infantil - Creche - 2 anos", "EI Creche",
			        "Educação Infantil - Creche - 3 anos", "EI Creche",
			        "Educação Infantil - 4 anos", "EI Pré-Escola",
			        "Educação Infantil - 5 anos", "EI Pré-Escola",
			        "Educação Infantil - Pré-Escola", "EI Pré-Escola",
			        "Ensino Fundamental - 1º ano", "EF Anos Iniciais",
			        "Ensino Fundamental - 2º ano", "EF Anos Iniciais",
			        "Ensino Fundamental - 3º ano", "EF Anos Iniciais",
			        "Ensino Fundamental - 4º ano", "EF Anos Iniciais",
			        "Ensino Fundamental - 5º ano", "EF Anos Iniciais",
			        "Ensino Fundamental - 6º ano", "EF Anos Finais",
			        "Ensino Fundamental - 7º ano", "EF Anos Finais",
			        "Ensino Fundamental - 8º ano", "EF Anos Finais",
			        "Ensino Fundamental - 9º ano", "EF Anos Finais",
			        "Ensino Médio - 1º ano", "Ensino Médio",
			        "Ensino Médio - 2º ano", "Ensino Médio",
			        "Ensino Médio - 3º ano", "Ensino Médio",
			        "Projeto de Vida Mind Lab - Cursos 1 e 2", "Projeto de Vida",
			        "Projeto de Vida Mind Lab - Cursos 3 e 4", "Projeto de Vida",
			        "Outros")
			```
		lineageTag: 5c0b67e0-93ab-4188-bb54-0e90ffad1e45
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Departamento 3'
		dataType: string
		lineageTag: 50bcb48d-c31d-428b-b709-cb130a9bfd25
		summarizeBy: none
		sourceColumn: Departamento 3

		annotation SummarizationSetBy = Automatic

	column 'Função.2'
		dataType: string
		lineageTag: 017d1343-7265-46fb-a8dd-6f49ed031c74
		summarizeBy: none
		sourceColumn: Função.2

		annotation SummarizationSetBy = Automatic

	column Instituição
		dataType: string
		lineageTag: c44dad8e-fcad-40df-82e3-832acb710f99
		summarizeBy: none
		sourceColumn: Instituição

		annotation SummarizationSetBy = Automatic

	column 'Departamento 4'
		dataType: string
		lineageTag: 7114ffcc-9a55-4b07-8bf1-b71d2d8c6bec
		summarizeBy: none
		sourceColumn: Departamento 4

		annotation SummarizationSetBy = Automatic

	column Personalizar
		dataType: string
		lineageTag: ba31c826-da2d-45d9-9ff8-201a50bc815b
		summarizeBy: none
		sourceColumn: Personalizar

		annotation SummarizationSetBy = Automatic

	column 'Status do cadastro'
		dataType: string
		lineageTag: 19b304ae-9d88-4c29-bfec-10577eba42c3
		summarizeBy: none
		sourceColumn: Status do cadastro

		annotation SummarizationSetBy = Automatic

	column 'Status vínculo'
		dataType: string
		lineageTag: 3ea30594-5dd3-471c-8742-4d5e456003e7
		summarizeBy: none
		sourceColumn: Status vínculo

		annotation SummarizationSetBy = Automatic

	partition dRelatoriodeUsuarios-9703d51e-1bbf-4bd0-8b60-76dda7bb49d8 = m
		mode: import
		queryGroup: Relatórios
		source =
				let
				    timestamp_now = DateTime.From(DateTimeZone.ToText(DateTimeZone.UtcNow())) - #duration(0, 3, 0, 0),
				    #"Data Extraída" = Date.From(timestamp_now),
				    date_text = Date.ToText(#"Data Extraída", "yyyy-MM-dd"),
				    string = date_text & KEY,
				    senha_codificada = codificacao(string),
				    Fonte = Json.Document(Web.Contents(LINK_FUNCAO, [Query=[senha=senha_codificada]])),
				    link = Fonte[link_usuarios],
				    path = Text.Split(link, "/"){5},
				    arquivo = Csv.Document(Web.Contents(CAMINHO_BUCKET & "/usuarios", [RelativePath=path])),
				    arquivo_cabecalho = Table.PromoteHeaders(arquivo, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(arquivo_cabecalho,{{"Data de admissão", type date}, {"Último Login", type datetime}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Tipo Alterado", "Função", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, false), {"Função.1", "Função.2"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Função.1", type text}, {"Função.2", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado2",{{"Função.1", "Função"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{"Matrícula", "Superior Direto"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas",{{"Instituição ", "Instituição"}}),
				    #"Texto em Maiúscula" = Table.TransformColumns(#"Colunas Renomeadas1",{{"Instituição", Text.Upper, type text}, {"Departamento 1", Text.Upper, type text}, {"Departamento 2", Text.Upper, type text}, {"Departamento 3", Text.Upper, type text}}),
				    #"Texto Limpo" = Table.TransformColumns(#"Texto em Maiúscula",{{"Instituição", Text.Trim, type text}, {"Departamento 1", Text.Trim, type text}, {"Departamento 2", Text.Trim, type text}, {"Departamento 3", Text.Trim, type text}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Texto Limpo", "Mesclado", each Text.Combine({[#"Instituição"], [Departamento 1], [Departamento 2], [Departamento 3]}, "$$"), type text),
				    #"Texto Limpo1" = Table.TransformColumns(#"Coluna Mesclada Inserida",{{"Função.2", Text.Clean, type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Texto Limpo1","Mediador","Professor(a)",Replacer.ReplaceText,{"Função"}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Valor Substituído", "Personalizar", each if [Função.2] = " Educação Infantil - Bebês" then "  Bebês" else if [Função.2] = " Educação Infantil - Crianças" then "  Crianças Bem Pequenas" else if [Função.2] = " Educação Infantil - 4 anos" then " 4 anos" else if [Função.2] = " Educação Infantil - 5 anos" then " 5 anos" else if [Função.2] = " Ensino Fundamental - 1º ano" then "1º ano" else if [Função.2] = " Ensino Fundamental - 2º ano" then "2º ano" else if [Função.2] = " Ensino Fundamental - 3º ano" then "3º ano" else if [Função.2] = " Ensino Fundamental - 4º ano" then "4º ano" else if [Função.2] = " Ensino Fundamental - 5º ano" then "5º ano" else if [Função.2] = " Ensino Fundamental - 6º ano" then "6º ano" else if [Função.2] = " Ensino Fundamental - 7º ano" then "7º ano" else if [Função.2] = " Ensino Fundamental - 8º ano" then "8º ano" else if [Função.2] = " Ensino Fundamental - 9º ano" then "9º ano" else if [Função.2] = " Projeto de Vida Mind Lab" then "Projeto de Vida" else if [Função.2] = " Ensino Médio - 1º ano" then "Ensino Médio - 1º ano" else if [Função.2] = " Ensino Médio - 2º ano" then "Ensino Médio - 2º ano" else if [Função.2] = " Ensino Médio - 3º ano" then "Ensino Médio - 3º ano" else "Outros"),
				    #"Linhas Filtradas" = Table.SelectRows(#"Coluna Condicional Adicionada", each ([Status vínculo] = "ACTIVE"))
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

