table fBUNivel0
	lineageTag: eaf1aa52-6cb6-4a1e-957d-f5deabe0571c

	measure 'ID C/ Acesso Últimos 30 Dias' = ```
			
			VAR Subtotal =
			    CALCULATE(
			        DISTINCTCOUNT('dLogdeAçoes'[Login]),
			        FILTER(ALL(dCalendario[Data]),
			            dCalendario[Data] <= MAX(dCalendario[Data]) &&
			            dCalendario[Data] >= MAX(dCalendario[Data]) - 30),
			            'dLogdeAçoes'[Tipo 2] = "Sim") 
			VAR Total = 
			    IF(ISBLANK(Subtotal),0,Subtotal)
			RETURN
			    Total 
			```
		formatString: #,0
		lineageTag: 5a368ed7-ad68-49e2-b006-f2e7b9e4a368

		changedProperty = FormatString

	measure 'ID Cadastrados' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        DISTINCTCOUNT('dIsat'[AditionalInformation.Login]),
			        FILTER(ALL(dCalendario[Data]),dCalendario[Data] <= MAX(dCalendario[Data])),
			        USERELATIONSHIP('dCalendario'[Data],'dIsat'[AditionalInformation.CreatedDate]))
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total 
			```
		formatString: #,0
		lineageTag: a325c789-dfea-43d8-a9dc-deb975e1a601

		changedProperty = FormatString

	measure '!!. Classificação da Saúde' =
			
			IF([!. Indicador da Saúde] < 25, "Zona Crítica",
			IF([!. Indicador da Saúde] >= 25 && [!. Indicador da Saúde] < 50, "Zona de Aperfeiçoamento",
			IF([!. Indicador da Saúde] >= 50 && [!. Indicador da Saúde] <= 75, "Zona de Qualidade", "Zona de Excelência")))
		lineageTag: 6e76aa85-a49f-489d-a6a0-498b69e5d8b7

	measure '!. Indicador da Saúde' = ```
			
			
			VAR PESO_TUTORIA = 7
			VAR PESO_ENGAJADOS_PLATAFORMA_PROF = 7
			VAR PESO_NPS = 1
			VAR PESO_MHS = 1
			VAR PESO_AVALIACAO_TUTORIA = 1
			VAR PESO_AVALIACAO_FORMADOR = 1
			VAR PESO_AVALIACAO_AULAS = 1
			VAR PESO_PROF_APLICANDO_AULAS = 1
			VAR PESO_ENTREGA_MATERIAIS = 7
			
			VAR PESO_X_PERCENTUAIS = 
			    (PESO_TUTORIA*'fBUNivel0'[% Professores Presentes em 1+ Tutoria]*100+
			    PESO_ENGAJADOS_PLATAFORMA_PROF*'fBUNivel0'[% Engajamento Professores]*100+
			    PESO_NPS*(('fBUNivel0'[NPS]+100)/2)+
			    PESO_MHS*'fBUNivel0'[MHS]*100+
			    PESO_AVALIACAO_TUTORIA*('fBUNivel0'[Média Avaliação Tutoria]*10)+
			    PESO_AVALIACAO_FORMADOR*('fBUNivel0'[Média Avaliação Formador]*10)+
			    PESO_AVALIACAO_AULAS*('fBUNivel0'[Média Avalie as Aulas]*10)+
			    PESO_PROF_APLICANDO_AULAS*'fBUNivel0'[% Professores Aplicação as Aulas]*100+
			    PESO_ENTREGA_MATERIAIS*dEntregaMateriais[Indicador Entrega]*100
			    )
			
			VAR SOMA_PESOS = 
			    (PESO_TUTORIA+
			    PESO_ENGAJADOS_PLATAFORMA_PROF+
			    PESO_NPS+
			    PESO_MHS+
			    PESO_AVALIACAO_TUTORIA+
			    PESO_AVALIACAO_FORMADOR+
			    PESO_AVALIACAO_AULAS+
			    PESO_PROF_APLICANDO_AULAS+
			    PESO_ENTREGA_MATERIAIS
			    )
			
			VAR RESULTADO = 
			    DIVIDE(PESO_X_PERCENTUAIS,SOMA_PESOS)
			
			RETURN RESULTADO
			```
		lineageTag: 70c1ee85-7564-4a13-92da-3ac006ed448a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Engajamento Alunos' = ```
			
			VAR Percentual = 
			    DIVIDE([Alunos C/ Avatar],[Alunos Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 64c4a891-87a1-4d46-aa04-1c1abc8b31c1

		changedProperty = FormatString

	measure '% MHS Detrator' = ```
			
			    DIVIDE([MHS Detrator],[MHS Total])
			```
		lineageTag: 48a19c80-7639-459a-9c1f-db42e6003945

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MHS Neutro' = ```
			
			    DIVIDE([MHS Neutro],[MHS Total])
			```
		lineageTag: 338ee435-4966-4ee0-9bc2-832548c7fe6e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% MHS Promotor' = ```
			
			    DIVIDE([MHS Promotor],[MHS Total])
			```
		lineageTag: 00156415-04bd-4304-bda8-342dcec4b75e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% NPS Detrator' = ```
			
			VAR Detratores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Resposta]<=6)
			VAR Percentual = 
			    DIVIDE(Detratores,[Respondentes NPS])
			RETURN 
			    IF(ISBLANK(Percentual),0,Percentual)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 22c03da2-69b9-4a1f-b46f-2f5dd5fcedc6

		changedProperty = FormatString

	measure '% NPS Neutro' = ```
			
			VAR Neutro = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Resposta]=7)
			        +
			     CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Resposta]=8) 
			VAR Percentual = 
			    DIVIDE(Neutro,[Respondentes NPS])
			RETURN 
			    IF(ISBLANK(Percentual),0,Percentual) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bea039b1-34da-4204-aa5f-c3c64b53f1ec

		changedProperty = FormatString

	measure '% NPS Promotor' = ```
			
			VAR Promotor = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Resposta]>=9)
			VAR Percentual =
			    DIVIDE(Promotor,[Respondentes NPS])
			RETURN 
			    IF(ISBLANK(Percentual),0,Percentual)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a0ad3475-1307-40e2-8d8b-2fd3d5f8591a

		changedProperty = FormatString

	measure '% Professores Aplicação as Aulas' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        DISTINCTCOUNT(ProfessoresAgendaAulaDada[CPF do Professor]),
			        dRelatoriodeUsuarios[Função]="Professor(a)"
			            )
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			VAR percentual = 
			    DIVIDE(total,[ID Cadastrados (prof)],0)
			RETURN percentual 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9589c1ec-9734-46ab-8a3e-c52159a14084

		changedProperty = FormatString

	measure '% Professores Presentes em 1+ Tutoria' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        dRelatoriodeUsuarios[Função] = "Professor(a)",
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição], "Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido, 'fBUNivel0'[ID Cadastrados (prof)])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual), 0, Percentual)
			RETURN Percentual_No_Blank
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 942b1281-f563-4a57-8830-501f6de04108

		changedProperty = FormatString

	measure '1ª Tutoria %' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"1ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank  
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ffd8246b-7688-46f8-a67c-e443d3c1216e

		changedProperty = FormatString

	measure '2ª Tutoria %' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"2ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank  
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eb05249e-d1a8-4773-8722-a405d13a9f4c

		changedProperty = FormatString

	measure '3ª Tutoria %' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"3ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank  
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b64f1117-eeea-46fa-a326-5335a449aa3f

		changedProperty = FormatString

	measure '4ª Tutoria %' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			       CONTAINSSTRING('dInscricoesDetalhado'[Lição],"4ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank  
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eb66276f-931c-4778-b41b-8db3561d74ec

		changedProperty = FormatString

	measure '5ª Tutoria %' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"5ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank  
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cbcbd628-6bc6-4c17-ba5b-2b2a4b47c8b7

		changedProperty = FormatString

	measure '6ª Tutoria %' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"6ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank  
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f4b23329-daca-432b-8557-65c62af7380f

		changedProperty = FormatString

	measure '7ª Tutoria %' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"7ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank  
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 34e67b5a-69f0-4599-b421-1df865a7c0ee

		changedProperty = FormatString

	measure '8ª Tutoria %' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"8ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank  
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 108763ed-c590-4144-99c0-9807f3fb8810

		changedProperty = FormatString

	measure '9ª Tutoria %' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"9ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank  
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bf54a3d3-6819-4aac-91e1-65b25118a764

		changedProperty = FormatString

	measure 'Alunos C/ Avatar' = ```
			
			VAR subtotal = 
			    SUM(dMindzup[Total Cadastrados Com Avatar])
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total 
			```
		formatString: #,0
		lineageTag: 529b19a8-fba2-4c4f-a29a-91b847cf0979

		changedProperty = FormatString

	measure 'Alunos Cadastrados' = ```
			
			VAR subtotal =     
			    SUM(dMindzup[Total Cadastrados])
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total 
			```
		formatString: #,0
		lineageTag: 5b0ee462-af2b-4cb6-be86-3a978a0bc0eb

		changedProperty = FormatString

	measure 'Cor NPS Detrator' = "#ed6f60"
		lineageTag: a5f58ce7-2480-42be-8377-b66226a1426a

	measure 'Cor NPS Neutro' = "#f6b900"
		lineageTag: b62ee0c1-8c70-4741-b32e-5dea84aca04d

	measure 'Cor NPS Promotor' = "#34aa4a"
		lineageTag: 33b74cfd-43af-4b82-a4be-82665d61260f

	measure 'Cores NPS' =
			
			IF([Legenda NPS] = "Zona Crítica", "#ed6f60",
			IF([Legenda NPS] = "Zona de Aperfeiçoamento", "#f6b900",
			IF([Legenda NPS] = "Zona de Qualidade", "#118dff", "#34aa4a")))
		lineageTag: 3554e77f-69f8-4a97-9286-c676f68e1dd8

	measure 'Legenda NPS' =
			
			IF('fBUNivel0'[NPS] <= 0, "Zona Crítica",
			IF('fBUNivel0'[NPS] > 1 && 'fBUNivel0'[NPS] <= 50, "Zona de Aperfeiçoamento",
			IF('fBUNivel0'[NPS] > 51 && 'fBUNivel0'[NPS] <= 75, "Zona de Qualidade", "Zona de Excelência")))
		lineageTag: 537f5f25-23b2-4076-addb-ab67b0f7427f

	measure MHS = ```
			
			VAR Muito_Desapontado = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[Resposta] = "Muito desapontado")
			VAR total = 
			    COUNTROWS(dMHS)
			VAR score = 
			    (Muito_Desapontado/total)
			RETURN 
			    IF(ISBLANK(score),0,score)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7565ba50-48b6-4cdd-98a6-e684c21dea63

		changedProperty = FormatString

	measure 'MHS 1' = ```
			
			VAR Muito_Desapontado = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[MHS] = "MHS 1",
			        dMHS[Resposta] = "Muito desapontado")
			VAR total = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[MHS] = "MHS 1")
			VAR score = 
			    (Muito_Desapontado/total)
			RETURN 
			    IF(ISBLANK(score),0,score)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 13fb848c-1d1d-40da-b4b3-623e08f53f80

	measure 'MHS 2' = ```
			
			VAR Muito_Desapontado = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[MHS] = "MHS 2",
			        dMHS[Resposta] = "Muito desapontado")
			VAR total = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[MHS] = "MHS 2")
			VAR score = 
			    (Muito_Desapontado/total)
			RETURN 
			    IF(ISBLANK(score),0,score)
			```
		lineageTag: 889954b5-5235-4558-bc59-dab441c82204

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MHS Detrator' = ```
			
			VAR Detratores = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[Resposta] = "Não sei responder, ou já não uso mais o produto")
			RETURN 
			    IF(ISBLANK(Detratores),0,Detratores)
			```
		formatString: 0
		lineageTag: 0eec3dcd-8592-4beb-8af0-34e14259a74b

	measure 'MHS Neutro' = ```
			
			VAR Neutro = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[Resposta] = "Indiferente")
			RETURN 
			    IF(ISBLANK(Neutro),0,Neutro)
			```
		formatString: 0
		lineageTag: cd791a9d-fb29-4066-b8e9-c272d9e54d75

	measure 'MHS Promotor' = ```
			
			VAR Promotor = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[Resposta] = "Muito Desapontado")
			RETURN 
			    IF(ISBLANK(Promotor),0,Promotor)
			```
		formatString: 0
		lineageTag: d26404c6-4f49-4dde-a0df-961bb3c6e82b

	measure 'MHS Total' =
			
			[MHS Detrator] + [MHS Neutro] + [MHS Promotor]
		formatString: 0
		lineageTag: b8cfe173-a9f4-4dfa-8e0f-2a7c0a0a266d

	measure NPS = ```
			
			VAR Detratores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Resposta] <= 6
			        //,'dNPS'[Data de resposta] >= DATE(2024, 7, 1)
			    )
			VAR Promotores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Resposta] >= 9
			        //,'dNPS'[Data de resposta] >= DATE(2024, 7, 1)
			    )
			VAR total = 
			    CALCULATE(
			        COUNTROWS(dNPS)
			        //,'dNPS'[Data de resposta] >= DATE(2024, 7, 1)
			    )
			VAR score = 
			    ((Promotores / total) * 100) - ((Detratores / total) * 100)
			RETURN 
			    IF(ISBLANK(score), 0, score)
			```
		lineageTag: 1aaeab08-9324-4712-a7dd-ea15d6def07f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NPS 1' = ```
			
			VAR Detratores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Nome da Origem] = "NPS 1",
			        dNPS[Resposta]<=6)
			VAR Promotores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Nome da Origem] = "NPS 1",
			        dNPS[Resposta]>=9)
			VAR total = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			            dNPS[Nome da Origem] = "NPS 1")
			VAR score = 
			    ((Promotores/total)*100)-((Detratores/total)*100)
			RETURN 
			    IF(ISBLANK(score),0,score) 
			```
		lineageTag: fcc02e1c-f3fc-49c9-a449-82064b0754df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NPS 2' = ```
			
			VAR Detratores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Nome da Origem] = "NPS 2",
			        dNPS[Resposta]<=6)
			VAR Promotores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Nome da Origem] = "NPS 2",
			        dNPS[Resposta]>=9)
			VAR total = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			            dNPS[Nome da Origem] = "NPS 2")
			VAR score = 
			    ((Promotores/total)*100)-((Detratores/total)*100)
			RETURN 
			    IF(ISBLANK(score),0,score)
			```
		lineageTag: 026b8e73-3f81-418d-b4e2-10ef94d52148

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NPS 3' = ```
			
			VAR Detratores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        AND(dNPS[Nome da Origem] = "NPS 3",
			            dNPS[Resposta]<=6))
			VAR Promotores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        AND(dNPS[Nome da Origem] = "NPS 3",
			            dNPS[Resposta]>=9))
			VAR total = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			            dNPS[Nome da Origem] = "NPS 3")
			VAR score = 
			    ((Promotores/total)*100)-((Detratores/total)*100)
			RETURN 
			    IF(ISBLANK(score),0,score)
			```
		lineageTag: 794fe68a-97ba-4568-8a37-d6dcdfef11ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NPS 4' = ```
			
			VAR Detratores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        AND(dNPS[Nome da Origem] = "NPS 4",
			            dNPS[Resposta]<=6))
			VAR Promotores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        AND(dNPS[Nome da Origem] = "NPS 4",
			            dNPS[Resposta]>=9))
			VAR total = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			            dNPS[Nome da Origem] = "NPS 4")
			VAR score = 
			    ((Promotores/total)*100)-((Detratores/total)*100)
			RETURN
			    IF(ISBLANK(score),0,score)
			```
		lineageTag: c9aee17f-c705-4a45-a5b9-c61c1c3abe23

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NPS Detrator' = ```
			
			VAR Detratores = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Resposta]<=6)
			RETURN 
			    IF(ISBLANK(Detratores),0,Detratores)
			```
		formatString: #,0
		lineageTag: 33630ac6-130e-44db-b077-945154604c2d

		changedProperty = FormatString

	measure 'NPS Neutro' = ```
			
			VAR Neutro = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Resposta]=7)
			        +
			     CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Resposta]=8) 
			RETURN 
			    IF(ISBLANK(Neutro),0,Neutro) 
			```
		formatString: #,0
		lineageTag: d5cd6732-bcb4-4a1e-b3d2-29d7d6f8f726

		changedProperty = FormatString

	measure 'NPS Promotor' = ```
			
			VAR Promotor = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Resposta]>=9)
			RETURN 
			    IF(ISBLANK(Promotor),0,Promotor)
			```
		formatString: #,0
		lineageTag: b44f9b22-58e9-4e4e-9ce9-e02fc2a09817

		changedProperty = FormatString

	measure 'Média Avaliação Formador' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        AVERAGE('dAvalieTutoria'[Resposta]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição], "Tutoria"),
			        'dAvalieTutoria'[Pergunta] = "Formador")
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal 
			```
		lineageTag: 92408e91-2e41-4eec-83cd-a4a6510dfdb7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Avaliação Tutoria' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        AVERAGE('dAvalieTutoria'[Resposta]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição], "Tutoria"),
			        'dAvalieTutoria'[Pergunta] = "Tutoria"
			        //, 'dAvalieTutoria'[Data de resposta] >= DATE(2024, 7, 1)
			    )
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal 
			```
		lineageTag: 2ed7bb5b-97f8-4d04-8f68-58299ece90e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Avalie as Aulas' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        AVERAGE('dAvalieasAulas'[Resposta - Nota]),
			        'dAvalieasAulas'[Resposta - Nota] <= 10,
			        ALL('dAvalieasAulas'))
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal 
			```
		lineageTag: 8a6d6a6f-e932-4533-b6d0-37693f48d880

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Formador 1ª Tutoria' = ```
			
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Formador],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"1ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: d5936817-b3e9-4858-ae4a-f8ea07193244

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Formador 2ª Tutoria' = ```
			
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Formador],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"2ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 06c465dd-5f6d-47b1-91c1-1dc9dc9fb6df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Formador 3ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Formador],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"3ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 23373aac-b977-4d86-9ada-f06813f516b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Formador 4ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Formador],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"4ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 4ed697b4-7513-404f-82a6-0a3d0293ea15

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Formador 5ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Formador],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"5ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 43601113-bdeb-4020-aa09-a35a001e070f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Formador 6ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Formador],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"6ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 5eb7299a-3e1e-4de3-9fd0-d108f59fc309

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Formador 7ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Formador],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"7ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 636afb03-0717-46ad-b7ef-7da8467c28e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Formador 8ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Formador],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"8ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 8b9a0e13-ec62-48ab-a61e-e927c5031d92

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Formador 9ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Formador],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"9ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: ad45424a-310b-4834-ba55-2a9c565a1721

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Tutoria 2ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Tutoria],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"2ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 3f1d2919-5469-4888-a9e4-06186aeadd3d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Tutoria 1ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Tutoria],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"1ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 9e11db07-5926-455a-93ea-5f7b0233f855

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Tutoria 3ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Tutoria],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"3ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 21029964-0030-450b-a4be-2f3aac74a920

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Tutoria 4ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Tutoria],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"4ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 8564585b-e90c-4564-95f0-1d08fc9150bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Tutoria 5ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Tutoria],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"5ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 684a832b-f77d-430e-8fb0-e8f3e8be8d21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Tutoria 6ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Tutoria],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"6ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: d271df38-137d-4fb8-b20c-d41513830d24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Tutoria 7ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Tutoria],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"7ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 1aeb344b-7d54-48b0-85f2-3eff9074ee9f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Tutoria 8ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Tutoria],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"8ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 2bf4b82b-0ba7-4a7c-85e1-2d785e10f608

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Tutoria 9ª Tutoria' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Tutoria],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"9ª Tutoria")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: de54f175-5d72-4010-8cdc-a3464d6f73c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Respondentes MHS' = ```
			
			VAR subtotal = 
			    COUNTROWS(dMHS)
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total
			```
		formatString: #,0
		lineageTag: 7e3887bb-ae07-4ca1-a5ef-38bf7288fd13

		changedProperty = FormatString

	measure 'Respondentes NPS' = ```
			
			VAR subtotal = 
			    COUNTROWS(dNPS)
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total 
			```
		formatString: #,0
		lineageTag: aba0170f-cf6b-4d2a-a2fa-c7caaa4be69d

		changedProperty = FormatString

	measure 'Range 2' = 0
		formatString: 0
		lineageTag: eb1452ed-8b18-4b18-84d4-bfff51120ad0

	measure 'Range 3' = 50
		formatString: 0
		lineageTag: 61ae3399-aa69-4ae7-aa66-a7a41b2b438a

	measure 'Range 4' = 75
		formatString: 0
		lineageTag: 2d3d27a2-b188-4d70-9f70-36b2bc9c697e

	measure 'Respondentes Tutoria (Avalie a Tutoria)' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        COUNTA('dAvalieTutoria'[Resposta]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição], "Tutoria"),
			        'dAvalieTutoria'[Pergunta] = "Tutoria"
			        )
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal 
			```
		formatString: 0
		lineageTag: fd02db57-03c3-4a3a-a6e4-be9347484a02

	measure 'Respondentes MHS 1' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[MHS] = "MHS 1")
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total 
			```
		formatString: 0
		lineageTag: 8f283dd1-d484-4fdb-b175-1af553a570b1

	measure 'Respondentes MHS 2' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[MHS] = "MHS 2")
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total 
			```
		formatString: 0
		lineageTag: 0e4011cc-ad4e-42a5-96a6-8af571cae077

	measure 'Respondentes NPS 1' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Nome da Origem] = "NPS 1")
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total 
			```
		formatString: 0
		lineageTag: 499b75a3-5b53-4622-b84b-ee974d826806

	measure 'Respondentes NPS 2' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Nome da Origem] = "NPS 2")
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total 
			```
		formatString: 0
		lineageTag: 04d64ce3-d7f7-4c09-b413-b82f8e4e3309

	measure 'Respondentes NPS 3' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Nome da Origem] = "NPS 3")
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total 
			```
		formatString: 0
		lineageTag: e4923dc3-5568-42a1-a418-183e24fa6698

	measure 'Respondentes NPS 4' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        COUNTROWS(dNPS),
			        dNPS[Nome da Origem] = "NPS 4")
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total 
			```
		formatString: 0
		lineageTag: f2178a3a-eaef-4084-a77c-e6b7f3b8cf87

	measure '% Engajamento Professores' = ```
			
			VAR Total_Cadastrado = 
			    [ID Cadastrados (prof)]
			VAR Percentual = 
			    DIVIDE([ID C/ Acesso Últimos 30 Dias (prof)],Total_Cadastrado)
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 93ac58f1-3738-4e99-b83d-196a2e3c5824

		changedProperty = FormatString

	measure 'ID´s sem acesso' = CALCULATE([ID Cadastrados],ISBLANK(dRelatoriodeUsuarios[Último Login]))
		formatString: 0
		lineageTag: a28cfd05-2ad9-4892-9c1c-55a81a54e272

	measure 'ID Cadastrados todos tipos' =
			
			CALCULATE([ID Cadastrados],ALL('dLogdeAçoes'[Login]))
		formatString: 0
		lineageTag: 1f90daf1-0d99-42e2-aff0-a4f6721d2d8d

	measure 'qtd professores' = ```
			CALCULATE(
			    DISTINCTCOUNT(dAvalieasAulas[Login]), 
			    dAvalieasAulas[Resposta - Data] <> 01/01/1899)
			```
		formatString: 0
		lineageTag: 9d839a9c-355d-4b77-8a0a-2cf17fadc671

	measure 'ID C/ Acesso Últimos 30 Dias (prof)' = ```
			
			VAR Subtotal =
			    CALCULATE(
			        DISTINCTCOUNT('dLogdeAçoes'[Login]),
			        dRelatoriodeUsuarios[Função]="Professor(a)",
			        FILTER(ALL(dCalendario[Data]),
			            dCalendario[Data] <= MAX(dCalendario[Data]) &&
			            dCalendario[Data] >= MAX(dCalendario[Data]) - 30),
			            'dLogdeAçoes'[Tipo 2] = "Sim") 
			VAR Total = 
			    IF(ISBLANK(Subtotal),0,Subtotal)
			RETURN
			    Total 
			```
		formatString: 0
		lineageTag: 5f512223-6d1e-4cae-b043-133d86026bb0

	measure 'ID Cadastrados (prof)' =
			
			CALCULATE(
			        [ID Cadastrados],
			        ALL('dLogdeAçoes'[Login]),
			        dRelatoriodeUsuarios[Função]="Professor(a)"
			        )
		formatString: #,0
		lineageTag: ea8a9eb3-3da0-4072-86e6-4cab0345408a

	measure '% Engajamento Geral' = ```
			
			VAR Total_Cadastrado = 
			    [ID Cadastrados]
			VAR Percentual = 
			    DIVIDE([ID C/ Acesso Últimos 30 Dias],Total_Cadastrado)
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0b141163-dea5-425e-828d-e7a9b9b85336

	measure 'MHS Público' = ```
			
			    CALCULATE(
			       [MHS],
			       fBUNivel0[Área] = "Público"
			       )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 00d126b0-5a16-4bdf-bbe4-0c8e3cb7dbfa

	measure 'Média Participação Tutorias' = ```
			
			VAR Ultima_Tutoria = [Última Tutoria]
			
			VAR Percentual = 
			    SWITCH(
			        TRUE(),
			        Ultima_Tutoria="Sem Tutorias Finalizadas","",
			        Ultima_Tutoria="","",
			        Ultima_Tutoria="1ª TUTORIA",[1ª Tutoria %],
			        Ultima_Tutoria="2ª TUTORIA",([1ª Tutoria %]+[2ª Tutoria %])/2,
			        Ultima_Tutoria="3ª TUTORIA",([1ª Tutoria %]+[2ª Tutoria %]+[3ª Tutoria %])/3,
			        Ultima_Tutoria="4ª TUTORIA",([1ª Tutoria %]+[2ª Tutoria %]+[3ª Tutoria %]+[4ª Tutoria %])/4,
			        Ultima_Tutoria="5ª TUTORIA",([1ª Tutoria %]+[2ª Tutoria %]+[3ª Tutoria %]+[4ª Tutoria %]+[5ª Tutoria %])/5,
			        Ultima_Tutoria="6ª TUTORIA",([1ª Tutoria %]+[2ª Tutoria %]+[3ª Tutoria %]+[4ª Tutoria %]+[5ª Tutoria %]+[6ª Tutoria %])/6,
			        Ultima_Tutoria="7ª TUTORIA",([1ª Tutoria %]+[2ª Tutoria %]+[3ª Tutoria %]+[4ª Tutoria %]+[5ª Tutoria %]+[6ª Tutoria %]+[7ª Tutoria %])/7,
			        Ultima_Tutoria="8ª TUTORIA",([1ª Tutoria %]+[2ª Tutoria %]+[3ª Tutoria %]+[4ª Tutoria %]+[5ª Tutoria %]+[6ª Tutoria %]+[7ª Tutoria %]+[8ª Tutoria %])/8,
			        Ultima_Tutoria="9ª TUTORIA",([1ª Tutoria %]+[2ª Tutoria %]+[3ª Tutoria %]+[4ª Tutoria %]+[5ª Tutoria %]+[6ª Tutoria %]+[7ª Tutoria %]+[8ª Tutoria %]+[9ª Tutoria %])/9,
			        "Não previsto"
			    )
			
			RETURN Percentual
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 24a2095b-e19a-4845-862a-558e5547ae79

	measure 'ID Cadastrados Prof Pub' = CALCULATE([ID Cadastrados (prof)],fBUNivel0[Área]="Público")
		formatString: 0
		lineageTag: 7b1e8310-7c9e-4604-9fc6-967c9e09f449

	measure 'Respondentes Formador' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        COUNTA('dAvalieTutoria'[Resposta]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição], "Tutoria"),
			        'dAvalieTutoria'[Pergunta] = "Formador"
			        )
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal 
			```
		formatString: 0
		lineageTag: 4eaa1146-4833-4251-aab7-f86a64c77db3

	measure 'Respondentes 2ª Tutoria' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        [Respondentes Tutoria (Avalie a Tutoria)],
			        CONTAINSSTRING('dAvalieTutoria'[Lição], "2ª Tutoria")
			    )
			VAR total = 
			    IF(ISBLANK(subtotal), 0, subtotal)
			RETURN total
			```
		formatString: 0
		lineageTag: f12c5623-f367-4d5b-89c1-9f7e8a2ae06f

	measure 'Respondentes 3ª Tutoria' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        [Respondentes Tutoria (Avalie a Tutoria)],
			        CONTAINSSTRING('dAvalieTutoria'[Lição], "3ª Tutoria")
			    )
			VAR total = 
			    IF(ISBLANK(subtotal), 0, subtotal)
			RETURN total
			```
		formatString: 0
		lineageTag: 4fbb489a-65cb-4bec-97f7-0a20ff743f3a

	measure 'Respondentes 4ª Tutoria' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        [Respondentes Tutoria (Avalie a Tutoria)],
			        CONTAINSSTRING('dAvalieTutoria'[Lição], "4ª Tutoria")
			    )
			VAR total = 
			    IF(ISBLANK(subtotal), 0, subtotal)
			RETURN total
			```
		formatString: 0
		lineageTag: c08efcee-c2c6-4fa8-a7f7-0f7abeef0581

	measure 'NPS Gestor' =
			
			CALCULATE(
			    [NPS],
			    FILTER(
			        dRelatoriodeUsuarios,
			        (dRelatoriodeUsuarios[Função] = "Coordenador(a)/Supervisor(a)/Assessor(a)" ||
			         dRelatoriodeUsuarios[Função] = "Diretor(a)" ||
			         dRelatoriodeUsuarios[Função] = "Gestor") &&
			        dRelatoriodeUsuarios[Instituição]<>"MIND LAB"
			    )
			)
		formatString: 0.00
		lineageTag: f32370dc-1335-4a12-a442-04d781c1650b

	measure 'Média Avaliação Tutoria prof' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        [Média Avaliação Tutoria],
			        dRelatoriodeUsuarios[Função]="Professor(a)"
			    )
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			
			RETURN subtotal
			
			```
		lineageTag: 5f04df35-3f6b-43f0-adb5-15a9d67cab5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '1ª Tutoria Concluído' = ```
			
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"1ª Tutoria")||CONTAINSSTRING('dInscricoesDetalhado'[Lição],"1ª Palestra"),
			        'dInscricoesDetalhado'[Status Final] == "Ok")
			```
		formatString: 0
		lineageTag: a46825b2-181f-49ec-9f67-a026abe808ef

	measure '2ª Tutoria Concluída' = ```
			
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"2ª Tutoria")||CONTAINSSTRING('dInscricoesDetalhado'[Lição],"2ª Palestra"),
			        'dInscricoesDetalhado'[Status Final] == "Ok")
			```
		formatString: 0
		lineageTag: 91af8939-aca0-46cf-8478-62186afcd57a

	measure '1ª Tutoria Em andamento' = ```
			
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"1ª Tutoria")||CONTAINSSTRING('dInscricoesDetalhado'[Lição],"1ª Palestra"),
			        'dInscricoesDetalhado'[Status na turma.2] == "Em andamento",'dInscricoesDetalhado'[Categoria] == "Tutorias")
			```
		formatString: 0
		lineageTag: 5a5f3b1d-f822-4bf1-b88c-1bdca9a566bd

	measure '1ª Tutoria Total' = [1ª Tutoria Concluído]+[1ª Tutoria Em andamento]
		formatString: 0
		lineageTag: b9178758-992d-448e-a71b-3e79fc49977e

	measure '2ª Tutoria Em andamento' = ```
			
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"2ª Tutoria")||CONTAINSSTRING('dInscricoesDetalhado'[Lição],"2ª Palestra"),
			        'dInscricoesDetalhado'[Status na turma.2] == "Em andamento",'dInscricoesDetalhado'[Categoria] == "Tutorias")
			```
		formatString: 0
		lineageTag: 5fa4920e-bb72-4a48-85b6-d0f822c3689b

	measure '2ª Tutoria Total' = [2ª Tutoria Concluída]+[2ª Tutoria Em andamento]
		formatString: 0
		lineageTag: 31a2b71e-4acd-4c21-8661-c73467fd1e25

	measure '3ª Tutoria Concluída' = ```
			
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"3ª Tutoria")||CONTAINSSTRING('dInscricoesDetalhado'[Lição],"3ª Palestra"),
			        'dInscricoesDetalhado'[Status Final] == "Ok")
			```
		formatString: 0
		lineageTag: 6bf9198d-0e25-45b9-a6bc-b8766b7d587b

	measure '3ª Tutoria Em andamento' = ```
			
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"3ª Tutoria")||CONTAINSSTRING('dInscricoesDetalhado'[Lição],"3ª Palestra"),
			        'dInscricoesDetalhado'[Status na turma.2] == "Em andamento",'dInscricoesDetalhado'[Categoria] == "Tutorias")
			```
		formatString: 0
		lineageTag: fd02f471-5645-4291-9cbb-7e7267a95305

	measure '3ª Tutoria Total' = [3ª Tutoria Concluída]+[3ª Tutoria Em andamento]
		formatString: 0
		lineageTag: 9a0e7873-39b1-447c-8ae8-dcab0f853dfd

	measure 'Respondentes Avalie as Aulas' = ```
			
			VAR subtotal = 
			    COUNTROWS('dAvalieasAulas')
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN total 
			```
		formatString: 0
		lineageTag: a1a7274e-bb12-46c9-a61c-1ab7856dcb5e

	measure 'Respondentes 5ª Tutoria' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        [Respondentes Tutoria (Avalie a Tutoria)],
			        CONTAINSSTRING('dAvalieTutoria'[Lição], "5ª Tutoria")
			    )
			VAR total = 
			    IF(ISBLANK(subtotal), 0, subtotal)
			RETURN total
			```
		formatString: 0
		lineageTag: 05b9589a-ba78-4918-8553-ee0ac940a882

	measure 'Respondentes 6ª Tutoria' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        [Respondentes Tutoria (Avalie a Tutoria)],
			        CONTAINSSTRING('dAvalieTutoria'[Lição], "6ª Tutoria")
			    )
			VAR total = 
			    IF(ISBLANK(subtotal), 0, subtotal)
			RETURN total
			```
		formatString: 0
		lineageTag: 25c417cc-f607-4f7d-aafa-ea7993121982

	measure 'Respondentes 1º Workshop' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        COUNTA('dAvalieTutoria'[Resposta]),dAvalieTutoria[Pergunta]="Tutoria",
			        CONTAINSSTRING('dAvalieTutoria'[Lição], "1º Workshop")
			    )
			VAR total = 
			    IF(ISBLANK(subtotal), 0, subtotal)
			RETURN total
			```
		formatString: 0
		lineageTag: c71108e2-e377-41ff-9858-6251ade6d9cc

	measure 'Respondentes 2º Workshop' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        COUNTA('dAvalieTutoria'[Resposta]),dAvalieTutoria[Pergunta]="Tutoria",
			        CONTAINSSTRING('dAvalieTutoria'[Lição], "2º Workshop")
			    )
			VAR total = 
			    IF(ISBLANK(subtotal), 0, subtotal)
			RETURN total
			```
		formatString: 0
		lineageTag: e3a273ca-5cab-450d-a4c2-55a7f7b0547b

	measure 'Média Formador 1º Workshop' = ```
			
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Formador (Workshop)],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"1º Workshop")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: a8f6d8a8-ef1e-403d-96e0-09e64f7a8e9c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Formador 2º Workshop' = ```
			
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Formador (Workshop)],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"2º Workshop")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 5d8ddeeb-3680-40e9-bb2a-cb2333db7f4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Tutoria 1º Workshop' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Tutoria (Workshop)],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"1º Workshop")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: cf99de29-2769-4540-bbe1-ac435f34244a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Tutoria 2º Workshop' = ```
			
			VAR subtotal = CALCULATE(
			            [Média Avaliação Tutoria (Workshop)],
			            CONTAINSSTRING('dAvalieTutoria'[Lição],"2º Workshop")
			
			            )   
			
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal
			```
		lineageTag: 725e4566-0382-4051-b555-88b45d40ab2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '1º Workshop %' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"1º Workshop"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank  
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a0b07697-319e-43d9-bde3-9024f82fbd6f

	measure '2º Workshop %' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"2º Workshop"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Percentual_No_Blank  
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a9225626-0681-423b-a835-521faf3e2d24

	measure ProfessoresTutoria = ```
			
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        dRelatoriodeUsuarios[Função] = "Professor(a)",
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição], "Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok"
			    )
			```
		formatString: 0
		lineageTag: 37deee38-796f-436a-9cf8-cc65e5755af8

	measure 'Média Avaliação Formador (Workshop)' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        AVERAGE('dAvalieTutoria'[Resposta]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição], "Workshop"),
			        'dAvalieTutoria'[Pergunta] = "Formador")
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal 
			```
		lineageTag: d375b3ed-7080-420a-8e0e-132be48fb31b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Avaliação Tutoria (Workshop)' = ```
			
			VAR subtotal = 
			    CALCULATE(
			        AVERAGE('dAvalieTutoria'[Resposta]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição], "Workshop"),
			        'dAvalieTutoria'[Pergunta] = "Tutoria")
			VAR total = 
			    IF(ISBLANK(subtotal),0,subtotal)
			RETURN subtotal 
			```
		lineageTag: c5171978-dc91-4459-858e-fcf090654742

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Respondentes NPS Gestor' = ```
			
			    CALCULATE(
			        [Respondentes NPS],
			        FILTER(
			            dRelatoriodeUsuarios,
			            (
			                dRelatoriodeUsuarios[Função] = "Coordenador(a)/Supervisor(a)/Assessor(a)" ||
			                dRelatoriodeUsuarios[Função] = "Diretor(a)" ||
			                dRelatoriodeUsuarios[Função] = "Gestor"
			            )
			        ),
			        FILTER(
			            fBUNivel0,
			            fBUNivel0[Área]= "Público" || fBUNivel0[Área]= "Privada"
			        )
			    )
			```
		formatString: 0
		lineageTag: 98ea1ed5-d9dc-4782-89c5-bb45d1e36d57

	measure 'Usuários cadastrados presentes em 1+ Tutoria' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição], "Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido, 'fBUNivel0'[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual), 0, Percentual)
			RETURN Concluido
			```
		lineageTag: d784c553-193b-435a-84d7-07b50f02bae2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '1º Workshop' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"1º Workshop"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Concluido  
			```
		formatString: 0
		lineageTag: a8fca1c9-da20-423f-81d4-c23d1ca1cf1e

	measure '2º Workshop' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"2º Workshop"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Concluido  
			```
		formatString: 0
		lineageTag: 40401b73-b338-4eff-8eee-9237f5146ca2

	measure '1ª Tutoria' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"1ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Concluido  
			```
		formatString: 0
		lineageTag: 1618aab5-ff8c-4faa-b508-386d48a4bb3b

	measure '2ª Tutoria' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"2ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Concluido  
			```
		formatString: 0
		lineageTag: 385c9e48-bb62-422a-a6c0-67a6989c3bd1

	measure '3ª Tutoria' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"3ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Concluido  
			```
		formatString: 0
		lineageTag: f358a469-075e-4c31-95d3-8f73cdf3be11

	measure '4ª Tutoria' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"4ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Concluido  
			```
		formatString: 0
		lineageTag: 6e83dc65-5df3-4888-898f-1ae7f0206207

	measure '5ª Tutoria' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"5ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Concluido  
			```
		formatString: 0
		lineageTag: 24ecdea3-d396-41ad-8020-0a9c3659a57f

	measure '6ª Tutoria' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"6ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Concluido  
			```
		formatString: 0
		lineageTag: 1c86da62-ad14-4058-8c65-735d7a9d524e

	measure '7ª Tutoria' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"7ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Concluido  
			```
		formatString: 0
		lineageTag: 6e7ef6dd-551e-4ff2-ab74-fde1f9624c78

	measure '8ª Tutoria' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"8ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Concluido  
			```
		formatString: 0
		lineageTag: 9e24891c-eae1-40b6-8549-c058618ecc22

	measure 'Desapontados sem o Programa' = ```
			
			VAR Desapontado = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[Resposta] = "Muito desapontado" || dMHS[Resposta] = "Um pouco desapontado"
			    )
			VAR total = 
			    COUNTROWS(dMHS)
			VAR score = 
			    (Desapontado/total)
			RETURN 
			    IF(ISBLANK(score),0,score)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 019e03b6-1fd5-4c54-85ed-e5fb2317bd1b

	measure 'Indiferentes sem o Programa' = ```
			
			VAR Indiferente = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[Resposta] = "Indiferente" 
			    )
			VAR total = 
			    COUNTROWS(dMHS)
			VAR score = 
			    (Indiferente/total)
			RETURN 
			    IF(ISBLANK(score),0,score)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3ba8a9ae-06bd-4f12-9053-c7131a3fa404

	measure 'Não sabem responder' = ```
			
			VAR naoseiresponder = 
			    CALCULATE(
			        COUNTROWS(dMHS),
			        dMHS[Resposta] = "Não sei responder, ou já não uso mais o produto" 
			    )
			VAR total = 
			    COUNTROWS(dMHS)
			VAR score = 
			    (naoseiresponder/total)
			RETURN 
			    IF(ISBLANK(score),0,score)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6e988195-487f-4355-825b-e672ca280d50

	measure '9ª Tutoria' = ```
			
			VAR Concluido = 
			    CALCULATE(
			        DISTINCTCOUNT('dInscricoesDetalhado'[Login]),
			        CONTAINSSTRING('dInscricoesDetalhado'[Lição],"9ª Tutoria"),
			        'dInscricoesDetalhado'[Status Final] = "Ok",
			        'dInscricoesDetalhado'[Categoria] = "Tutorias"
			    )
			VAR Percentual = 
			    DIVIDE(Concluido,fBUNivel0[ID Cadastrados])
			VAR Percentual_No_Blank = 
			    IF(ISBLANK(Percentual),0,Percentual)
			RETURN Concluido  
			```
		formatString: 0
		lineageTag: 34b0600e-c0e1-4c3c-97ed-fd95ce7d6130

	measure 'Contagem Professores Aulas Aplicadas' = ```
			
			    CALCULATE(
			        DISTINCTCOUNT(ProfessoresAgendaAulaDada[CPF do Professor]),
			        dRelatoriodeUsuarios[Função]="Professor(a)"
			    )
			```
		formatString: 0
		lineageTag: a417c1a4-3fda-4e5f-8968-fbeb429fe626

	measure 'ID Cadastrados (Auxiliar)' =
			
			CALCULATE(
			        [ID Cadastrados],
			        ALL('dLogdeAçoes'[Login]),
			        dRelatoriodeUsuarios[Função]="Auxiliar/Assistente"
			        )
		formatString: 0
		lineageTag: 52b45ca0-8871-4265-a76b-67a32f8d8fa5

	measure 'ID Cadastrados (coordenador)' =
			
			CALCULATE(
			        [ID Cadastrados],
			        ALL('dLogdeAçoes'[Login]),
			        dRelatoriodeUsuarios[Função]="Coordenador(a)/Supervisor(a)/Assessor(a)"
			        )
		formatString: 0
		lineageTag: efb390e2-66b3-46f3-8f93-fa7e640e7c92

	measure 'ID Cadastrados (Diretor)' =
			
			CALCULATE(
			        [ID Cadastrados],
			        ALL('dLogdeAçoes'[Login]),
			        dRelatoriodeUsuarios[Função]="Diretor(a)"
			        )
		formatString: 0
		lineageTag: 9e83d39f-08f8-48bb-b989-e9ef5dd84c9b

	measure 'ID Cadastrados (gestor)' =
			
			CALCULATE(
			        [ID Cadastrados],
			        ALL('dLogdeAçoes'[Login]),
			        dRelatoriodeUsuarios[Função]="Gestor"
			        )
		formatString: 0
		lineageTag: cca5e590-c7e8-4e73-aa33-db0875a26943

	column Instituição = LOOKUPVALUE(fBUNivel0[BusinessUnitName],fBUNivel0[BusinessUnitID],PATHITEM(PATH(fBUNivel0[BusinessUnitID],fBUNivel0[ParentBusinessUnitID]),1))
		lineageTag: 659a6e7e-f319-49d5-9da9-83efbd40def4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Departamento 1' = LOOKUPVALUE(fBUNivel0[BusinessUnitName],fBUNivel0[BusinessUnitID],PATHITEM(PATH(fBUNivel0[BusinessUnitID],fBUNivel0[ParentBusinessUnitID]),2))
		lineageTag: a59537fb-0bbc-4ca2-ac20-c0662c59c54f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Departamento 2' = LOOKUPVALUE(fBUNivel0[BusinessUnitName],fBUNivel0[BusinessUnitID],PATHITEM(PATH(fBUNivel0[BusinessUnitID],fBUNivel0[ParentBusinessUnitID]),3))
		lineageTag: cb5e9647-c418-448b-a533-f2e30afdaa60
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Departamento 3' = LOOKUPVALUE(fBUNivel0[BusinessUnitName],fBUNivel0[BusinessUnitID],PATHITEM(PATH(fBUNivel0[BusinessUnitID],fBUNivel0[ParentBusinessUnitID]),4))
		lineageTag: 0459b00c-2851-4438-88d3-25e2d246606d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Mesclado = UPPER(fBUNivel0[Instituição]&"$$"&fBUNivel0[Departamento 1]&"$$"&fBUNivel0[Departamento 2]&"$$"&fBUNivel0[Departamento 3])
		lineageTag: 9dbd6746-c9dd-4a0e-bd4c-002c71ee184d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column BusinessUnitID
		dataType: string
		lineageTag: 3d64dd1b-7f85-459e-829a-d21130fc8bc6
		summarizeBy: none
		sourceColumn: BusinessUnitID

		annotation SummarizationSetBy = Automatic

	column ClientUniqueIdentifier
		dataType: string
		lineageTag: e065a3bd-9ea5-49c6-b8f5-b793cdff9070
		summarizeBy: none
		sourceColumn: ClientUniqueIdentifier

		annotation SummarizationSetBy = Automatic

	column BusinessUnitName
		dataType: string
		lineageTag: e1db001a-d64a-4b11-8ef0-b6101b8bc0a8
		summarizeBy: none
		sourceColumn: BusinessUnitName

		annotation SummarizationSetBy = Automatic

	column BusinessUnitTypeID
		dataType: int64
		formatString: 0
		lineageTag: 6195fbd1-70fa-4abc-85ff-f7ac4b914b96
		summarizeBy: count
		sourceColumn: BusinessUnitTypeID

		annotation SummarizationSetBy = Automatic

	column BusinessUnitType_Identifier
		dataType: string
		lineageTag: 8842e7f7-be90-4d80-9296-98ee30614ae7
		summarizeBy: none
		sourceColumn: BusinessUnitType_Identifier

		annotation SummarizationSetBy = Automatic

	column BusinessUnitStatusID
		dataType: int64
		formatString: 0
		lineageTag: e874b7e6-ebb2-42f6-88ff-ab6f0ab0a42b
		summarizeBy: count
		sourceColumn: BusinessUnitStatusID

		annotation SummarizationSetBy = Automatic

	column BusinessUnitStatus_Identifier
		dataType: string
		lineageTag: 1e9968a7-be66-41a1-9baa-7f6522779d2e
		summarizeBy: none
		sourceColumn: BusinessUnitStatus_Identifier

		annotation SummarizationSetBy = Automatic

	column ParentBusinessUnitID
		dataType: string
		lineageTag: 0c67cc3b-209d-40a5-9fe1-b47e872fc659
		summarizeBy: none
		sourceColumn: ParentBusinessUnitID

		annotation SummarizationSetBy = Automatic

	column IsDeleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 736c8475-516b-4cf2-9faf-113fab01b706
		summarizeBy: none
		sourceColumn: IsDeleted

		annotation SummarizationSetBy = Automatic

	column AuditCreatedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: c5aa0919-707c-4a30-affd-86c11600c86e
		summarizeBy: none
		sourceColumn: AuditCreatedDate

		variation Variation
			isDefault
			relationship: 8f0710f9-6c93-436a-a4c7-ce0aae10ec25
			defaultHierarchy: LocalDateTable_15407988-8d80-4925-a5ce-d85c6d69a482.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column AuditLastUpdatedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: dad8c849-0f76-434e-ba0c-29019dd2237e
		summarizeBy: none
		sourceColumn: AuditLastUpdatedDate

		variation Variation
			isDefault
			relationship: 03ad2553-ef1b-41a5-b66a-f639e1ef6141
			defaultHierarchy: LocalDateTable_721c77bf-93cb-4cbf-a95d-b707fc3e9c33.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Área = RELATED(dCupons[Área])
		lineageTag: 29add7aa-69f3-4eb1-b1c9-7b2a7399beb5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Responsável Comercial' = CALCULATE(FIRSTNONBLANK(dResponsaveis[Rep. Comercial],TRUE()),ALL(dRelatoriodeUsuarios[Função]))
		lineageTag: 8bc623c2-f02d-4612-ad9e-d7bdfc8cbf52
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Responsável Operações' =
			--RELATED(dResponsaveis[Op. Responsável])
			LOOKUPVALUE(dResponsaveis[Op. Responsável],dResponsaveis[Cliente],fBUNivel0[Instituição])
		lineageTag: 2465969a-94ec-445a-84e6-ec486fd5966f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Departamento 4' = LOOKUPVALUE(fBUNivel0[BusinessUnitName],fBUNivel0[BusinessUnitID],PATHITEM(PATH(fBUNivel0[BusinessUnitID],fBUNivel0[ParentBusinessUnitID]),5))
		lineageTag: f6e35b12-7f6a-4c8b-8a1a-e598724b9393
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fBUNivel0-dc50b172-b969-4214-b783-74a16372da5a = m
		mode: import
		queryGroup: 'Instituição + Departamentos'
		source = ```
				let
				    Rota = "businessunits",
				    Fonte = List.Generate (() => 
				        [Result = if Table.IsEmpty(fAPIISAT(Rota,1)) then null else fAPIISAT(Rota,1),Page=1],
				        each [Result] <> null,
				        each [Result = if Table.IsEmpty(fAPIISAT(Rota,[Page]+1)) then null else fAPIISAT(Rota,[Page]+1),Page=[Page]+1],
				        each [Result]),
				    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Column1 Expandido" = Table.ExpandTableColumn(#"Convertido para Tabela", "Column1", {"Column1"}, {"Column1.1"}),
				    #"Column1.1 Expandido" = Table.ExpandRecordColumn(#"Column1 Expandido", "Column1.1", {"BusinessUnitID", "ClientUniqueIdentifier", "BusinessUnitName", "BusinessUnitTypeID", "BusinessUnitType_Identifier", "BusinessUnitStatusID", "BusinessUnitStatus_Identifier", "ParentBusinessUnitID", "IsDeleted", "AuditCreatedDate", "AuditLastUpdatedDate"}, {"BusinessUnitID", "ClientUniqueIdentifier", "BusinessUnitName", "BusinessUnitTypeID", "BusinessUnitType_Identifier", "BusinessUnitStatusID", "BusinessUnitStatus_Identifier", "ParentBusinessUnitID", "IsDeleted", "AuditCreatedDate", "AuditLastUpdatedDate"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Column1.1 Expandido",{{"ClientUniqueIdentifier", type text}, {"BusinessUnitName", type text}, {"BusinessUnitTypeID", Int64.Type}, {"BusinessUnitType_Identifier", type text}, {"BusinessUnitStatusID", Int64.Type}, {"BusinessUnitStatus_Identifier", type text}, {"IsDeleted", type logical}, {"AuditCreatedDate", type datetime}, {"AuditLastUpdatedDate", type datetime}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each ([IsDeleted] = false) and ([BusinessUnitStatus_Identifier] = "CACT" or [BusinessUnitStatus_Identifier] = "DACT"))
				in
				    #"Linhas Filtradas"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

