table formacoes_completa
	lineageTag: 3637d153-8f2c-44d9-b576-624eea85f27d

	column ID_TRILHA
		dataType: int64
		formatString: 0
		lineageTag: 89296e08-d566-4293-9b08-87f255d1a270
		summarizeBy: none
		sourceColumn: ID_TRILHA

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: cf4bb899-e5b9-44be-b9a4-7e0ff30070e8
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 88a23b17-46b8-4a42-b375-a1b519c7fefc
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: 9274d4f6-8223-47dd-83f8-0bc50bf1cf35
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column TagList
		dataType: string
		lineageTag: 43598a60-1d5c-4bac-bbf0-0937c9edaf94
		summarizeBy: none
		sourceColumn: TagList

		annotation SummarizationSetBy = Automatic

	column IsDeleted
		dataType: string
		lineageTag: 6f046801-0e13-46f9-90f2-197addea8a76
		summarizeBy: none
		sourceColumn: IsDeleted

		annotation SummarizationSetBy = Automatic

	column CreatedDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: aac23cc2-dd4e-47ad-8199-1796b8d1eea4
		summarizeBy: none
		sourceColumn: CreatedDate

		variation Variation
			isDefault
			relationship: 5daf7a02-4e4a-4afc-b4dc-64f5962e91e5
			defaultHierarchy: LocalDateTable_a1ffb483-8a9a-4115-bd04-1537ee42ab99.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column UpdatedDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e9aed1a7-00d9-4dbb-a694-11a7db28ab34
		summarizeBy: none
		sourceColumn: UpdatedDate

		variation Variation
			isDefault
			relationship: 289288e1-d178-4a64-97ad-97803900b853
			defaultHierarchy: LocalDateTable_061b0a03-aec3-4e19-8b42-cce01dfea8be.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EstimatedDuration
		dataType: string
		lineageTag: c7f6c261-b17f-4ee2-9702-2b51e98ebfab
		summarizeBy: none
		sourceColumn: EstimatedDuration

		annotation SummarizationSetBy = Automatic

	column EstimatedDurationFormatted
		dataType: string
		lineageTag: 557d29fe-91f5-4690-9f58-06d9aa2b1d88
		summarizeBy: none
		sourceColumn: EstimatedDurationFormatted

		annotation SummarizationSetBy = Automatic

	column TrackStatusIdentifier
		dataType: string
		lineageTag: f59a31a4-cb00-4d15-a753-ac6987e7c259
		summarizeBy: none
		sourceColumn: TrackStatusIdentifier

		annotation SummarizationSetBy = Automatic

	column InProgressClassCount
		dataType: string
		lineageTag: 553b54a5-8551-4332-b281-36b74fb3669a
		summarizeBy: none
		sourceColumn: InProgressClassCount

		annotation SummarizationSetBy = Automatic

	column CanBeDeleted
		dataType: string
		lineageTag: c3135988-497d-4846-a083-df43fee0be97
		summarizeBy: none
		sourceColumn: CanBeDeleted

		annotation SummarizationSetBy = Automatic

	partition formacoes_completa = m
		mode: import
		queryGroup: Relatórios
		source =
				let
				    timestamp_now = DateTime.From(DateTimeZone.ToText(DateTimeZone.UtcNow())) - #duration(0, 3, 0, 0),
				    #"Data Extraída" = Date.From(timestamp_now),
				    date_text = Date.ToText(#"Data Extraída", "yyyy-MM-dd"),
				    string = date_text & KEY,
				    senha_codificada = codificacao(string),
				    Fonte = Json.Document(Web.Contents(LINK_FUNCAO, [Query=[senha=senha_codificada]])),
				    link = Fonte[link_formacoes_completa],
				    path = Text.Split(link, "/"){5},
				    arquivo = Csv.Document(Web.Contents(CAMINHO_BUCKET & "/formacoes_completa", [RelativePath=path])),
				    arquivo_cabecalho = Table.PromoteHeaders(arquivo, [PromoteAllScalars=true]),
				    #"Colunas Renomeadas" = Table.RenameColumns(arquivo_cabecalho,{{"ID", "ID_TRILHA"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{""}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"ID_TRILHA", Int64.Type}, {"CreatedDate", type date}, {"UpdatedDate", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

