table MKT
	lineageTag: f901fd16-04b8-44a1-8691-3d399c38b4c3

	measure 'Indicador de reputação online' = ```
			
			        CALCULATE(MAX(MKT[Resultado]),MKT[OKR]="Indicador de reputação online")
			```
		formatString: 0
		lineageTag: 57594891-659d-4a08-b012-cf14324c2741

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Indicador Matérias' = ```
			
			        CALCULATE(MAX(MKT[Resultado]),MKT[OKR]="Matérias veículadas")
			```
		formatString: 0.00
		lineageTag: ef489b38-8a9b-4488-a033-ef3b1106efe0

	column OKR
		dataType: string
		lineageTag: 3e0dcae8-2a00-4e06-b6e5-e32ea54159d6
		summarizeBy: none
		sourceColumn: OKR

		annotation SummarizationSetBy = Automatic

	column 'Descrição do OKR'
		dataType: string
		lineageTag: 26a74849-995c-49f5-89c3-874c7e530406
		summarizeBy: none
		sourceColumn: Descrição do OKR

		annotation SummarizationSetBy = Automatic

	column Resultado
		dataType: double
		formatString: 0.00
		lineageTag: d618934b-8206-478d-a170-fda6524f875c
		summarizeBy: sum
		sourceColumn: Resultado

		annotation SummarizationSetBy = Automatic

	partition MKT = m
		mode: import
		queryGroup: 'Consultas sheets'
		source =
				let
				    Fonte = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1oxWnwXoojvSDSqd8U9a4bbblxeKUsyLBr_k_lYzhT_I/edit#gid=1017037701"),
				    #"Cupom - 2023_Table" = Fonte{[name="Resumo OKR",ItemKind="Table"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Cupom - 2023_Table", [PromoteAllScalars=true]),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Cabeçalhos Promovidos",{{"01/07/2023", "Resultado"}, {"Filtro para tudo a partir de 01/07/2023 até 30/06/2024", "Descrição do OKR"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{"31/12/2023"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"Resultado", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

